### ISSUE TITLE
Allow license expired notice to be dismissed temporarily

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1078]
When a license key is expired or invalid, we display a notice in the admin. Currently this notice cannot be dismissed. Right or wrong, we get some users that are unhappy about this. I'm proposing that we allow it to be dismissed temporarily (perhaps two weeks or a month). After the time period is passed, if the license is still expired or invalid, the notice is displayed (and allowed to be dismissed) again.

**Comment by michaelbeil** [comment]
:+1:

**Comment by DrewAPicture** [comment]
Added a PR.

**Comment by pippinsplugins** [comment]
Excellent, will get it tested soon.

**Comment by DrewAPicture** [comment]
Simplest way to test this is simply to check if the notice gets dismissed and the transient set. You could also hardcode a smaller duration to ensure the transient expires and notice is restored following expiration.

**Comment by pippinsplugins** [comment]
All looks good!

**Comment by TheCrowned** [comment]
Why would the dismissing be temporary? Once the user is told that the license is expired, and he doesn't want to renew, why bother him so often?

**Comment by pippinsplugins** [comment]
@TheCrowned Very simple. It's bad business not to and that person is continuing to use our premium plugin with an expired license. It's also negligent of a store owner to continue to run a site with an expired license as that leaves them susceptible to bugs and, more important, security flaws that are fixed in newer versions,

**Comment by TheCrowned** [comment]
Well, I guess this really comes down to one's own business views, other than really being a bug. I believe that if I, as site administrator/webmaster, click on _Dismiss notice_ and don't do anything about it (i.e. I don't purchase a renewal), it's my responsibility and my fault if something goes wrong due to bugs fixed in newer releases.

A concrete example is my case: I purchased AffiliteWP to try the affiliate thing, and it has not been successful at all (not a plugin issue, it's the affiliates). So there's no reason for me to uninstall the plugin, because I do have a couple affiliates who could generate revenue, but it's still not worth for me to update a plugin that brought in no revenue at all for me. So when I click on _Dismiss notice_, I'm saying "I know it's outdated and may be bugged, but I'm not gonna upgrade right now." I feel like the plugin asking me again 10 days later the same thing is just like if my message was not heard. Site management is a responsibility, and if I decide that a outdated version is fine for me, I think my choice should be respected without further notice.

**Comment by pippinsplugins** [comment]
Thank you for the feedback. You are more than welcome to disable the notice via the WordPress plugin's API if you wish.
