### ISSUE TITLE
Allow more than 2 decimal places in referral totals

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1083]
We have had users want to use currencies that utilize more than two decimal places, such as Bitcoin. Currently we force all referral amounts to two decimal places. Let's remove that restriction.

For now we'll do it simply with a filter.

**Comment by pippinsplugins** [comment]
`affwp_format_amount()` and `affwp_sanitize_amount()` already support changing the decimal places through `affwp_sanitize_amount_decimals` and `affwp_format_amount_decimals`, we just need to add it to `affwp_calc_referral_amount`.

**Comment by pippinsplugins** [comment]
Whoops, committed to master.

@sumobi could you test this?

**Comment by sumobi** [comment]
@pippinsplugins looks good to me
![screen shot 2016-01-29 at 7 57 49 pm](https://cloud.githubusercontent.com/assets/52581/12669124/a4ea7bca-c6c2-11e5-9ec7-4fb69a9976a0.png)

**Comment by michaelbeil** [comment]
Perfect!

**Comment by jabaco** [comment]
hello, it has been another whole month, 3 updates and I do not see the implementation of bitcoin decimals... This is very frustrating since every time there is an update, I have to manually update core files. This is a really basic milestone for you to implement and will be of great benefit to all your customers like me that are using bitcoin as payment gateway.
