### ISSUE TITLE
Adjust referral rate for returning customers

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1113]
It would be nice to have a way to adjust the referral rate for returning customers that are attached to an affiliate. Perhaps this could be something that works in tandem with Lifetime Commissions, while also providing a similar functionality with the tracking cookie as it stands in core.

**Comment by worldtravlr** [comment]
:+1:

**Comment by sumobi** [comment]
@michaelbeil When you say "returning customers that are attached to an affiliate" do you mean the customers who have the affiliate's ID currently stored in a cookie?

**Comment by michaelbeil** [comment]
Yes, precisely @sumobi.

**Comment by sumobi** [comment]
@michaelbeil so just to clarify:

1. Customer A uses Affiliate X's referral link and purchases.
2. Affiliate X is awarded 20% commission.
3. Customer A returns to the store (before their browser cookie expires) and purchases again
4. Affiliate X is awarded a higher or lower rate than before, perhaps 30% commission.

Is that correct? If so, then the customer needs to be stored somehow with the affiliate so when they return again, the system knows it's the customer's second purchase. This is how Lifetime Commissions works with its `Lifetime Referral Rate` setting - a returning customer who is linked to an affiliate awards the affiliate a different commission. 

This feature would essentially be Lifetime Commissions, but only for cookie tracking. Lifetime Commissions has an issue open for expiration dates so maybe its a feature better suited for LC. Ie set the lifetime expiration to 30 days and if the customer returns and purchases (after the initial purchase), the affiliate will receive the lifetime referral rate. At 30 days, the customer and the affiliate are no longer linked. It also has the advantage of being much more reliable since a cookie can be deleted, or a different browser can be used.

**Comment by worldtravlr** [comment]
Interesting Idea.  Just to pipe in some thoughts.

I would not use this feature for my own setup, but it could be interesting to also have this built into normal affiliate cookie tracking as an option.  For example if the cookie window is a generous 60 days or longer, but maybe after a first purchase and/or 30 days the commission goes down a percentage per day/week/month.  In this way the affiliate gets paid 100% of possible commission for a first sale within 30 days, but for future purchases the commission is reduced slightly.

As you say with cookie tracking may not be that accurate, but most people are creatures of habit using the same browser to purchase even it if is a month or two later.  It does seem to make more sense for lifetime commissions and be a more solid option, but I could see how it could be helpful for both.

We are an affiliate via reffersion for some partners and their cookies seem to track forever, but after 60 days, we get no credit for that customer purchase.  This helps us know the conversion rate even if it takes the customer 60+ days to purchase, but is also a bit depressing to see in the dashboard :8ball: 

![screen shot 2016-03-30 at 7 59 52 am](https://cloud.githubusercontent.com/assets/6686642/14144566/75cd11e4-f64d-11e5-8ef9-e30461c44365.jpg)

**Comment by michaelbeil** [comment]
I think this would be better suited as a feature in LC.

**Comment by michaelbeil** [comment]
Closing in favor of LC implementation.
