### ISSUE TITLE
RCP: Undefined indexes when registering while logged in

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1116]
I'm seeing the following notices when purchasing a subscription in RCP while logged in:

Notice: Undefined index: user_name in /Users/pippin/Sites/edd/wp-content/plugins/affiliate-wp/includes/integrations/class-rcp.php on line 249

Notice: Undefined variable: user_id in /Users/pippin/Sites/edd/wp-content/plugins/affiliate-wp/includes/integrations/class-rcp.php on line 258

**Comment by michaelbeil** [comment]
Oh noes.

**Comment by sumobi** [comment]
This seems to be happening when you purchase a subscription while logged in, and with a discount code.

When a subscription is purchased it's firing the `increase_uses` function:
https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/class-rcp-discounts.php#L220 

This in turn is firing the `update()` function:
https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/class-rcp-discounts.php#L344

Inside the update function is the `rcp_edit_discount` action hook:
https://github.com/restrictcontentpro/restrict-content-pro/blob/master/includes/class-rcp-discounts.php#L392

AffiliateWP uses this `rcp_edit_discount` hook in the RCP integration, for the function that is throwing the 2 notices:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-rcp.php#L25

Judging by the `update_discount_affiliate` function, it's only supposed to be run from within the admin, but as we can see from the update function, the action hook also fires on the front-end of the website.

The 2 notices also appear when editing the RCP discount from within the admin, but only when a discount is saved without an affiliate added to the `Affiliate Discount?` field.

In addition to the notices, I found another bug whereby if you set an affiliate in the `Affiliate Discount?` field, but then try to change it to another affiliate and save, it retains the previous affiliate. Looking in the database I can see the `affwp_discount_rcp_` metakey being created twice for the same discount code. 

Will submit a PR in the next day or so.

**Comment by pippinsplugins** [comment]
Good work tracking that down, it was confusing the heck out of me.

**Comment by sumobi** [comment]
@pippinsplugins First pass: https://github.com/AffiliateWP/AffiliateWP/pull/1154

This PR fixes a few things:

1. The PHP notices on both the front-end when purchasing a membership using a discount code.

2. The PHP notices shown in the admin when updating a discount with no affiliate added to the discount.

3. The issue where you couldn't change the affiliate added to the discount with a new one, since it stored a duplicate meta key.

Once you've had a look at the PR I'll need to also make some minor tweaks to the `store_discount_affiliate()` function also. Here's why:

Wherever there's an ajax affiliate search in AffiliateWP and you click an affiliate in the search popup, it stores the affiliate's user ID in a hidden input field. I see why that's useful but it will fail to save the correct user ID in some instances:

1. When the site admin manually types in the affiliate's username, sees the affiliate they want, and finishes off typing without selecting the affiliate from the popup search box.

2. When there's already an affiliate entered and the site admin deletes it then enters a new username, again without using the affiliate search.

As you'll see in the PR I'm proposing we **always** work out the user ID based on the posted username, and not rely on the user ID posted along with the user_id field. This means the user ID will be always be correct when the affiliate username is typed in by the site admin, or the username is selected from the search popup. It's an extra step but much better IMO, unless I'm missing something obvious.

**Comment by sumobi** [comment]
@pippinsplugins since you haven't disagreed (yet :8ball: ) I'm going to go ahead and finish off the `store_discount_affiliate()` function.

**Comment by michaelbeil** [comment]
An eight ball is coming?

**Comment by pippinsplugins** [comment]
@sumobi :+1:

**Comment by michaelbeil** [comment]
Ran into this as well ...

```
Notice: Undefined index: user_name in /srv/www/wordpress-default/wp-content/plugins/AffiliateWP/includes/integrations/class-rcp.php on line 249

Notice: Undefined variable: user_id in /srv/www/wordpress-default/wp-content/plugins/AffiliateWP/includes/integrations/class-rcp.php on line 258
An error occurred

Status: 400

Message: No such coupon: 50
```

**Comment by sumobi** [comment]
This is now ready for testing https://github.com/AffiliateWP/AffiliateWP/pull/1154

**Comment by pippinsplugins** [comment]
:+1:
