### ISSUE TITLE
Integration for Wishlist Members

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#114]

**Comment by fjarrett** [comment]
I tried for several hours to provide an integration for this plugin, but was unable to for several reasons. Here were my findings:

#### Lack of hooks
The WishList plugin does not provide any universally uniform hooks when purchases are made. You might expect something like `wlm_purchase` or `wlm_order` that would be fired with every order, no matter what cart integration is being used. No such hooks exist.

The shopping cart hooks that do exist have [no documentation](http://codex.wishlistproducts.com/shopping-cart-hooks/), and there are some hooks like `wlm_shoppingcart_rebill` that exist in the codebase but aren't acknowledged in the codex at all. In most cases I could not get the provided hooks to fire properly - but perhaps that was due to my configuration, which leads us to the next point...

#### Too many possible configurations
The plugin is very flexible and has a LOT of options, presumably so you can customize the behavior to your exact liking. However the _downside_ with this is that there is not a clear path for how a typical site will be configured.

When there are 15 ways to do the same thing, and hooks are fired on some actions but not others, it makes controlled user acceptance testing virtually impossible. We might get integration working with one use case only to discover 14 other cases that don't work.

#### Conclusions
Until the WishList Member plugin provides some sort of universally uniform hooks for payments/orders there can be no simple integration with AffiliateWP. Our plugin must be able to determine the payment amount on a purchase in order to award a referral. It must also know when payments are revoked, cancelled, or declined in order to cancel referrals. WishList does not provide any easy mechanism to gathering this information (to my knowledge).

Happy to be proved wrong on all this.

**Comment by pippinsplugins** [comment]
Unless the WIshlist developers choose to address these issues, I think the best approach is simply to use the conversion script short code.

@sumobi any objections to closing this and setting that up as the standard method?

**Comment by sumobi** [comment]
@pippinsplugins Nope, looks like we'll just leave as is: http://docs.affiliatewp.com/article/86-wishlist-member
