### ISSUE TITLE
Can't create new field type with callback

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1273]
I've been trying to create a new field type (multiselect) but receiving the following message:

> The callback function used for the affwp_rta_page_ids setting is missing.

It used to be that you could do this by adding `type` to the setting:

`'type' => 'multiselect'`

And defining the callback to match:

`function multiselect_callback() { ... }`

Also followed the example here:
https://github.com/AffiliateWP/AffiliateWP/pull/774#issue-95260803

But this gives the same result:

![screen shot 2016-05-07 at 3 39 17 pm](https://cloud.githubusercontent.com/assets/52581/15090041/18781a1c-146a-11e6-9f29-ce4dbda329d8.png)

Related: https://github.com/AffiliateWP/AffiliateWP/issues/677

**Comment by pippinsplugins** [comment]
We have it set up to only use the `_callback` postfix if the `callback` parameter is excluded. Also the `_callback` postfix only works for methods inside of the settings class.
```php
$callback = ! empty( $option['callback'] ) ? $option['callback'] : array( $this, $option['type'] . '_callback' );
```

Pass in the `callback` parameter.

**Comment by sumobi** [comment]
@pippinsplugins Yeah I did actually try that originally - using the 'callback' parameter yielded the same results. Want to give it a quick test and see if you can add your own field?

**Comment by DrewAPicture** [comment]
@sumobi Were you trying to register a new field type *in core* for use by core and add-ons, or was this strictly from an add-on? I'm asking because I got this to work just fine in an add-on. To be honest, if you're specifying your own callback, you don't even need to supply a field type:

```php
function multiselect_setting( $settings ) {
	$settings['general']['custom'] = array(
		'name'     => 'Multiselect',
//		'type'     => 'multiselect',
		'callback' => 'multiselect_callback'
	);

	return $settings;
}
add_filter( 'affwp_settings', 'multiselect_setting' );

function multiselect_callback( $args ) {
	$multiselect  = '<select multiple>';
		$multiselect .= '<option value="edd">Easy Digital Downloads</option>';
		$multiselect .= '<option value="affwp">AffiliateWP</option>';
		$multiselect .= '<option value="rcp">Restrict Content Pro</option>';
	$multiselect .= '</select>';

	echo $multiselect;
}
```

**Comment by sumobi** [comment]
@DrewAPicture Aha! I know why it wasn't working for me. My callback was inside my class. As soon as I dropped it into a separate file everything works fine. Thanks for looking into that.

**Comment by DrewAPicture** [comment]
Inside a class it should still work as long as you pass the instance to the
'callback' argument, e.g. `'callback' => array( $this, 'my_callback_method'
)`
On Jun 2, 2016 11:56 PM, "Andrew Munro" <notifications@github.com> wrote:

@DrewAPicture <https://github.com/DrewAPicture> Aha! I know why it wasn't
working for me. My callback was inside my class. As soon as I dropped it
into a separate file everything works fine. Thanks for looking into that.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/AffiliateWP/AffiliateWP/issues/1273#issuecomment-223497052>,
or mute the thread
<https://github.com/notifications/unsubscribe/AA8wR_G-X8CCBXfvdmZHfug2eOElJMw_ks5qH8IXgaJpZM4IZWCP>
.

**Comment by sumobi** [comment]
Bingo, that's what I was missing. Thanks and closing.
