### ISSUE TITLE
Image thumbnail in Affiliates -> Creatives list table

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1280]
Creatives are inherently visual. And since they have the option of associating with an image, it might be nice to show a thumbnail (or fallback) in the list table to indicate which ones have images, and a thumbnail of that image if set.

**Comment by sumobi** [comment]
@ramiabraham I can take this over if you'd like

**Comment by DrewAPicture** [comment]
@sumobi Do eet.

**Comment by sumobi** [comment]
@AffiliateWP/core Ready for testing

<img width="1463" alt="screen shot 2016-12-15 at 7 53 35 pm" src="https://cloud.githubusercontent.com/assets/52581/21251159/38c4a714-c300-11e6-82d0-7c77d6dd2e7e.png">

Rather than loading the entire image into the list table, I opted to load the thumbnail. Primarily because:

1. All images are the same size and it will be less visually distracting. Also, if a skyscraper banner is used, each row will still take up the same amount of space
2. It will be faster to load the thumbnail as opposed to the full image size

The only downside that I can see is that the thumbnail isn't a full representation of the creative since the creative could be a very specific size, e.g. 480x60.

It's only meant to be a preview though so I don't think this is too big of an issue Anyone agree/disagree? I also decided we don't need a placeholder image if there isn't an image added to a creative.

**Comment by pippinsplugins** [comment]
How about changing the `Image` column name to `Image Preview`? I think that would adequately take care of concerns about it not showing the complete image.

**Comment by sumobi** [comment]
@pippinsplugins sounds good to me

**Comment by sumobi** [comment]
@pippinsplugins updated

**Comment by pippinsplugins** [comment]
@sumobi images aren't showing up for me. It's just a blank space.

**Comment by sumobi** [comment]
@pippinsplugins Do you have an image added to the creative? (of course you have)

Thoughts on a filter or option to hide the entire `image preview` column? I personally would prefer not to have this new column since it makes each row exponentially.

**Comment by pippinsplugins** [comment]
Yep, definitely uploaded an image. I tried it with an existing creative and a brand new one with a new image upload.

:+1: to adding a new filter option.

**Comment by sumobi** [comment]
Ok I'll have a look, I also tested with new creatives etc and it worked fine. Bet it's something small.

**Comment by sumobi** [comment]
@pippinsplugins what's your thumbnail size set to in media -> settings? You do see the column though right? It's just empty. Do you see anything at all in the source for each `td`?

@AffiliateWP/core Can I get a couple more peeps to test this

**Comment by pippinsplugins** [comment]
@sumobi 150x150.

It's working now, so not sure what was up before.

**Comment by DrewAPicture** [comment]
The image preview looks good to me.

@sumobi Could we also link the image preview to the Edit screen for the creative? First thing I did subconsciously was try to click on it and I think others might too.

**Comment by sumobi** [comment]
Good idea

**Comment by sumobi** [comment]
Added a `affwp_creative_table_columns` filter as per https://github.com/AffiliateWP/AffiliateWP/issues/1280#issuecomment-268064992

**Comment by sumobi** [comment]
Think we're good to go on this

**Comment by pippinsplugins** [comment]
Merged!
