### ISSUE TITLE
Reposition Affiliates Action Links in Admin

### ISSUE THREAD

**Issue by lukemcdonald** [AffiliateWP/AffiliateWP#131]
The action links on the Affiliates page seem like they should be located under the affiliates name on hover. This functionality would follow more along the lines of how core handles these types of links; take the Posts list table for example.

![actions-placement](https://cloud.githubusercontent.com/assets/299173/2627395/0f1e0e76-be05-11e3-9583-ab126c0887b5.png)

This would also help with the table layout issues mentioned in #130.

**Comment by pippinsplugins** [comment]
@DrewAPicture as our main "core conventions" guy, do you have strong opinions one way or another on this?

**Comment by DrewAPicture** [comment]
I would actually agree with moving the action links back regardless of how *tall* it makes the page. At the same time, I would strongly caution *against* using buttons. Buttons/icons can be subjective and introduce confusion if you don't know what they signify. It's actually one of my biggest pet peeves with interfaces – nobody likes to try guessing what symbols mean.

**Comment by pippinsplugins** [comment]
Let's move them.

**Comment by pippinsplugins** [comment]
PR submitted.
![screen shot 2016-08-30 at 9 58 10 pm](https://cloud.githubusercontent.com/assets/1034109/18114500/1ddcfae8-6efd-11e6-8bcd-f7f25a4c0b4c.png)

**Comment by sumobi** [comment]
@pippinsplugins No issues with regards to the actual links. I gotta say, I'm not a huge fan of moving the ID to the Name column - was there an issue open for this? I understand it saves an extra column but:

1. It makes the assumption that the ID is more important than the username. In reality, some site owners prefer seeing the ID, some prefer the username. Similar to how an admin sets the preferred referral format (username or ID).

2. It's now harder to scan for the ID since they will never align vertically. Some affiliate names will be much longer than others, perhaps in rare cases even spanning onto 2 lines.

3. You can't order the column by the ID anymore, only the name. Ie I can't quickly see who was the first affiliate 1-100, or 100 to 1.

4. It sounds silly but a site owner may now think the ID is part of the name, or at least it could create a few tickets. "What does the ID refer to?" they might ask. At least before it was clear that the number was an "Affiliate ID".

Related: How many times does a site owner realistically need to edit the affiliate's WP user account by clicking on their name and going to WP profile screen? Since a site admin is on the "affiliates" screen we should only show actions related to affiliates. 

How about we link the affiliate's name to the edit affiliate screen as per above and also leave the "edit" link in the actions menu (sometimes it's easier having more than 1 link). This is much more likely since there are many options that the admin might need to change.  We can then show a link to the affiliate's WP user profile from the edit affiliate screen.

**Comment by sumobi** [comment]
@ramiabraham @wordmaid @DrewAPicture @michaelbeil Would love to hear your thoughts ^

**Comment by wordmaid** [comment]
I wholeheartedly agree the Affiliate ID should remain in its own column, for all of the reasons mentioned above. It does look quite messy with the Name and the Affiliate ID are now so close. 

Will this also affect reporting? As in, will the Affiliate ID appear in the same column as the Name when an Affiliates CSV is exported? I would imagine many customers would hope the report would look exactly as the admin Affiliates page does (I personally would...).

As a user side note, I also **always** click on the name of the affiliate by accident, thinking I'll land on the Edit Affiliate screen, but I am sent to the Edit User WordPress profile screen, which is fairly annoying. I agree that as we are in the Affiliates screen already, clicking the affiliate's name, ID, or username should take me to the Edit Affiliate screen. If there is a link to the Edit User screen from the Edit Affiliate screen, I could happily access their WordPress profile that way. I'm not sure I would visit the WordPress Edit User screen on a regular basis for an affiliate (unless it was password-related).

**Comment by pippinsplugins** [comment]
@wordmaid would not affect reporting in any way.

I'm happy to change the name linking but let's do that in a separate issues.

I moved the affiliate ID for two reasons:

1. Frees up real estate. The table looks pretty poor on small screens before the changes here
2. It more closely mimics core and other large plugins (Woo, EDD, RCP, etc)

I'll reverse it and see if I can make room with it.

**Comment by pippinsplugins** [comment]
`Affiliate ID` column restored.

**Comment by pippinsplugins** [comment]
Going to merge this into release/1.9 for internal beta. We can continue tweaking as necessary.

**Comment by michaelbeil** [comment]
It looks decent on mobile: 
 
![screen shot on 2016-08-31 at 15-52-12](https://cloud.githubusercontent.com/assets/4752949/18145940/f416835a-6f92-11e6-9cb4-43d1fc7754b2.png)


I think the affiliate id and username column look great together. Also, the inline actions work and display nicely. 
![screen shot 2016-08-31 at 3 53 29 pm](https://cloud.githubusercontent.com/assets/4752949/18146000/1c8cd2a8-6f93-11e6-9446-262f630650c1.png)

I can see that removing the affiliate ID column altogether would be beneficial to the screen real estate, but it could render confusion on the user's end. I do appreciate the look of RCP, WC, and EDD's lists that include an ID with customer/user, but I guess having the ability to sort by ID makes me think that we should leave the ID column for now.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by sumobi** [comment]
👍  What's an example of where core uses IDs? I'm all for doing what core does if it's relevant. In this instance I think that Affiliate IDs are much more important than Product IDs (WC, EDD etc) whereby the admin doesn't really need to know at a glance which product has which ID.

**Comment by pippinsplugins** [comment]
There isn't one, I didn't mean core.

**Comment by sumobi** [comment]
Ahh I see, you meant AffiliateWP, not WordPress 👍

**Comment by DrewAPicture** [comment]
@pippinsplugins To be fair, we could still save some real estate by using an `ID` only label for the column. We're already on the Affiliates management screen, having the label be `Affiliate ID` is kind of redundant.

**Comment by DrewAPicture** [comment]
For that matter, we could even move the then `ID` column to precede the Affiliate name on the left (right of the checkbox).

**Comment by sumobi** [comment]
I'm all for saving screen space but changing it from `Affiliate ID` to `ID` doesn't actually save that much space. I also believe that changing it to `ID` may cause confusion since it could be mistaken for the User ID. This is primarily because the `ID` column would sit next to the `Username` column, which _is_ the WordPress username.

If we change it to `ID` we'd also need to change `Affiliate ID` to `ID` on the edit affiliate screen for consistency, otherwise we'd have ID on one screen and Affiliate ID on the next. Again, this would cause confusion. And then we'd have `ID` and `User ID` on the edit screen. What's the `ID` for? (as customers would say) 

My vote is to keep it as `Affiliate ID`.

**Comment by wordmaid** [comment]
From a user perspective, my vote is for `Affiliate ID` as well.

**Comment by pippinsplugins** [comment]
Ok, `Affiliate ID` it is.

**Comment by michaelbeil** [comment]
Sounds good to me.
