### ISSUE TITLE
Zippy Courses: referrals generated via subscription payments set to "Pending"

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1401]
@jwondrusch @ejonasson 

A customer is experiencing an issue whereby referrals generated for her course via a subscription payment are set to Pending status, versus single payment (lump sum) referrals which are correctly set to Unpaid status. I've been able to replicate this locally when testing, and have been using Zippy Courses version 1.2.4 (same as the customer) with AffiliateWP version 1.8.4.

Should subscription payment referrals also be set to Unpaid status automatically, as the payment has been collected from the customer, and the transaction is complete?

**Comment by ejonasson** [comment]
@wordmaid I was able to replicate this as well. We'll aim to get you a fix for this before the weekend, early next week at the latest. Thanks!

**Comment by pippinsplugins** [comment]
@ramiabraham could you please test the attached PR?

**Comment by wordmaid** [comment]
@ejonasson Awesome thanks!

**Comment by wordmaid** [comment]
@ejonasson I've tried testing this, unfortunately it did not work for me and the referral was still created as Pending for a subscription-based product. @sumobi, would you please be able to try testing this as well?

**Comment by ejonasson** [comment]
@wordmaid Can you check under "Zippy Courses" -> "Orders" to make sure the order you made is showing as Active or Complete in Zippy Courses? If it isn't, that would explain the issue.

There are some situations where an order may not be marked as active. For example, if Webhooks aren't set up in Stripe, then the subscription will be stuck as pending because Zippy isn't alerted of a successful payment. For your testing purposes, manually setting the subscription to "Active" should serve the same purpose.

If the Zippy order is showing as Active or Complete, let me know. Thanks!

**Comment by wordmaid** [comment]
@ejonasson That could explain it! The status was Pending and I just changed the status to Active and the referral was set to Unpaid. Thanks! :)

**Comment by sumobi** [comment]
@ejonasson Thanks for the PR!

Works great here also. Setting Zippy Courses order from `pending` to `completed` changes the referral from `pending` to `unpaid`. 

@pippinsplugins Happy to merge if you are.

**Comment by pippinsplugins** [comment]
Merged.
