### ISSUE TITLE
Incorrect referral amounts due to decimal separator

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1475]
Entering `1000.00` shows as `1,00`

Steps to reproduce:

1. Change `Decimal Separator` to `,` (comma)
2. Add a new referral of `1000`
3. Referral amount shows as `1,00` on referrals screen

Going back into edit the referral correctly shows it as `1000.00` since it doesn't use the comma. We should probably make this screen consistent with the decimal separator set under settings.

Ticket (with video)
https://secure.helpscout.net/mailbox/7c3a9e4da50293a7/205524/

**Comment by DrewAPicture** [comment]
Took me a few minutes to track this down. This bug was actually introduced in 7b1d141dd for #1322 when we added a call to `affwp_format_amount()` inside of `affwp_currency_filter()`. Not having been terribly familiar with common conventions at the time, .e.g truly formatting amounts for display using *both* `functions: `affwp_currency_filter( affwp_format_amount( $amount ) )` all over the place, it seemed like the logical fix.

Now realizing common convention, we should remove the extra `affwp_format_amount()` call from `affwp_currency_filter()` and apply the double-function in several places thought "fixed" in #1322.

**Comment by DrewAPicture** [comment]
Added a PR: #1476

There may be other places where we're using `affwp_currency_filter()` and `affwp_format_amount()` should also be used. We should do a full audit.

**Comment by pippinsplugins** [comment]
PR looks good at first glance.

**Comment by sumobi** [comment]
@DrewAPicture @pippinsplugins Works great here
