### ISSUE TITLE
Revert charset schema change in 1.8.6

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#1479]
PR: #1487

@ramiabraham raises a good point that with no current expectation in 1.8.x that people will be running *at least* WP 4.2 (where the core charset was bumped to `utf8mb4`), waiting to bump the charset in AffWP might be a good idea.

It's also worth considering the possibility of an increased support burden coinciding with the charset change. It would be a little easier to swallow if we're also bumping the WP minimum 4.4 at the same time.

Porting it to 1.9 should be fairly simple, but for anybody running master, you'd need to run a routine to change your charsets back and probably restart MySQL.

**Comment by ramiabraham** [comment]
Waiting until `1.9` to bump to `utf8mb4` as noted by @drew above gives us (admittedly nebulous) benefits:

- Shake out potential issues with the sometimes strange voodoo world of unicode
- I think that #1423 and related encoding issues are certainly important, but it's not a widely-reported issue (that I know of) for customers at this time. 
- Waiting another month or so in order to get it all in at once might provide us _no_ benefit, or it may provide enough time to highlight _some_ encoding issue, perhaps with core, or perhaps with one or more add-ons not accounting for `utf8mb4` strings.

That said, we'll only know the impact of this routine once we pull the trigger. The [implementation](https://github.com/AffiliateWP/AffiliateWP/blob/da5a06b6ab83377fc4188a214328542fb0ae5ae2/includes/admin/class-upgrades.php#L448) would be cool to test on 4.4 and 4.5 with a test site that has:

- no previously-entered, failed `utf8mb4 string insertions
- many previously-entered, failed `utf8mb4 string insertions
- a large amount of data (hundreds of each object or more)

**Comment by sumobi** [comment]
I am afraid of unicode

**Comment by DrewAPicture** [comment]
Added a PR: #1487

**Comment by DrewAPicture** [comment]
Note: I've left the logging bits in class-upgrades.php should we want to use them in the future.

**Comment by DrewAPicture** [comment]
@AffiliateWP/core: Gist to revert your tables' `charset` and `collation` values: https://gist.github.com/DrewAPicture/5f6b9b022e5a8eed21feb63e7da84578

**Comment by pippinsplugins** [comment]
Ready to close I believe @DrewAPicture, yes?

**Comment by DrewAPicture** [comment]
@pippinsplugins Yeah. With #1487 merged, this is done.
