### ISSUE TITLE
Add user profile REST controls?

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1635]
We should add API key controls to the user profile edit screen.

**Comment by pippinsplugins** [comment]
I don't agree with this actually. We've had them in EDD since API was originally added, but we didn't start with an API keys table. That table was introduced later.

I greatly prefer the list table version and do not feel showing them on profiles is necessary or important.

Happy to be overruled though!

**Comment by michaelbeil** [comment]
The list table seems fine by me.
