### ISSUE TITLE
Add "Generated by" username or name to Payouts

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1718]
For tracking purposes and extra accountability I think it would be great if we can include a timestamp somewhere on the individual **Payout** screen. Perhaps this could go next to the date, or be its own line. I think next to the date would be fine, though.

Similarly, I think it would be great to show who generated the payout, if possible, and show their username. This provides an extra measure of security and accountability for site owners and other admins on their site. Potential language could be "Generated by:" or "Generated by User:". Could also potentially include "User ID:" next to their username?

Implementing these two things may help us avoid unnecessary support tickets if a customer wonders why a payout was generated and is adamant they didn't do it themselves.

**Comment by michaelbeil** [comment]
That seems like a legitimate concern and something that we should get added.

**Comment by pippinsplugins** [comment]
I agree.

**Comment by DrewAPicture** [comment]
I think we should absolutely look at adding "owners" for payouts, e.g. "Generated by" though this would require a bit of architectural work. So let's tackle that part in 1.9.5.

For 1.9.4, I've added a PR, #1733, which simply exposes the payout time in addition to the date on View Payout. Looks like this:
![time](https://cl.ly/0X2W0X1V181a/Screen%20Shot%202016-10-20%20at%202.42.14%20PM.png)

**Comment by DrewAPicture** [comment]
Payout time was added in #1733, for which I added #1736 (for record keeping), moving this to 1.9.5 to tackle the "Generated by" logic.

**Comment by wordmaid** [comment]
🙌 🙌 🙌

**Comment by DrewAPicture** [comment]
Added a PR: #1742 

The PR implements a 'Generated By' column in the Payouts list table as well as on Payout > View. Note, this introduces a schema change and a new `owner` column to the Payouts table. This means that payouts generated prior to 1.9.5 will have no owner, notated as '(none)'. And just like with affiliates, if the payout had an owner and the user has since been deleted, it will be notated as (user deleted)'.

Clicking the owner name in the list table filters payouts by that specific owner. Clicking the owner name in Payout > View takes you to the edit user page for that user.

**Payouts list table:**
![list table](https://cl.ly/1U1j2h3U183y/Screen%20Shot%202016-10-21%20at%205.57.40%20PM.png)

**Payout > View:**
![payout view](https://cl.ly/172z2d0b000r/Screen%20Shot%202016-10-21%20at%205.58.39%20PM.png)

**Comment by DrewAPicture** [comment]
To actually test this, you need to run the schema update yourself first, such as through the debug bar console:
```sh
affiliate_wp()->affiliates->payouts->create_table()
```

**Comment by DrewAPicture** [comment]
Also added REST and CLI support for payout owners ;)

**Comment by pippinsplugins** [comment]
PR looks good to me.
