### ISSUE TITLE
Moving inline graph JS to footer

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1755]
A customer has mentioned their graph in the affiliate area disappeared after installing this plugin: https://wordpress.org/plugins/scripts-to-footerphp/

This plugin moves all the enqueued scripts to the site footer. Since jQuery is also moved below the graph's inline JS it breaks - jQuery is no longer defined.

Any reason why we can't load the injected JS into the footer, perhaps at a much later priority so we're 100% sure jQuery has been loaded?

**Comment by sumobi** [comment]
FYI there is an option in the plugin to "Keep jQuery in Header" which will prevent the graph from breaking but for performance reasons the customer was not happy about this and would prefer to move all scripts.

**Comment by DrewAPicture** [comment]
Added a PR: #1756 

It's not the prettiest solution in the world, but it _does_ get the job done in my testing. Since `wp_add_inline_script()` was introduced in 4.5 and we're still 4.4 minimum, it includes back-compat support back to 4.2.

To test:
1. Install and activate the [Scripts To Footer]() plugin
2. Visit the Affiliate Area > Graphs tab or Reports page and confirm that the Graph isn't displaying
3. Add the following code snippet to enable attaching the inline JS to the flot.js enqueue:
```
add_filter( 'affwp_append_graph_js_to_flot', '__return_true' );
```
4. Revisit the Affiliate Area > Graphs tab or Reports page and confirm that the Graph is now displaying as expected.

**Comment by sumobi** [comment]
@DrewAPicture awesome, works for me

**Comment by pippinsplugins** [comment]
I like it.

**Comment by michaelbeil** [comment]
Works good here @DrewAPicture.

**Comment by DrewAPicture** [comment]
So after we added this, we circled back around to say that maybe we should just always hook it to the flot.js script, that way if something moves flot to the footer, this will automagically come along with it with needing to activate a filter. Working on a new PR.

**Comment by DrewAPicture** [comment]
Added a new PR: #1767
