### ISSUE TITLE
affiliate_wp_campaigns table error

### ISSUE THREAD

**Issue by AiratHalitov** [AffiliateWP/AffiliateWP#1795]
Can you check your plugin when you changing DB prefix?

I can't view table "myprefix_affiliate_wp_campaigns" in phpmyadmin, cause it's "in use". 
Is it normal behaviour or bug?

```
# mysqldump mydbname > mydbname.sql
mysqldump: Got error: 1356: View 'mydbname.myprefix_affiliate_wp_campaigns' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them when using LOCK TABLES
```

**Comment by michaelbeil** [comment]
It looks like you are logged into phpmyadmin with a user that does not have permissions to look at the campaigns view. Your MySQL user does not necessarily need root access to create/access a view, but you will need to add the required privileges like Create_view_priv and Super_priv as shown here: [Privileges Provided by MySQL](http://dev.mysql.com/doc/refman/5.7/en/privileges-provided.html). Make sure that the user has the CREATE VIEW privilege in order to use the CREATE VIEW statement for the view.

**Comment by AiratHalitov** [comment]
@michaelbeil Thanks!
But my user have all permissions in this database (including CREATE VIEW).
MySQL root user can't view this table too. 
I think I need drop all affiliate wp data and reinstall plugin.

**Comment by AiratHalitov** [comment]
Problem solved after reinstalling plugin (with deleting all affiliatewp data)

**Comment by michaelbeil** [comment]
Glad to hear it!
