### ISSUE TITLE
Sub-Affiliates (Tiered Affiliate Program)

### ISSUE THREAD

**Issue by zackkatz** [affiliatewp/AffiliateWP#181]
If an affiliate refers another affiliate to sign up, allow them to earn a percentage of the sub-affiliate's sales.

* Sub-affiliate referred $100 sale
* Sub-affiliate gets default rate (20%): $20
* Parent affiliate gets commission as well (5%): $5

This can be seen as spammy; it's essentially the beginning of a pyramid scheme, but it also has legitimate uses.

Or more advanced implementation: http://support.qualityunit.com/237945-Forced-Matrix

**Comment by maurisrx** [comment]
This would be an awesome addon for affiliateWP. Is there a news update for this addon? Users may can't use PayPal because they prohibit multi level marketing https://www.paypal.com/ms/webapps/helpcenter/helphub/article/?solutionId=FAQ858&topicID=&m=ARA despite they say "PayPal reserves the right to permit certain multi-level marketing programs at its sole discretion".

**Comment by sumobi** [comment]
@maurisrx There was a 3rd party add-on released for MLM, see: http://affiliatewp.com/multi-level-marketing-add-on-released/

**Comment by maurisrx** [comment]
@sumobi What a quick response! Thank you for the info.

**Comment by sumobi** [comment]
You're welcome @maurisrx!

Since a 3rd party add-on was released I'm going to go ahead and close this issue out.
