### ISSUE TITLE
Show affiliate status in Edit Affiliate screen

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1837]
I thought that the affiliate status was already visible on the Edit Affiliate screen, but it isn't there currently. I think it would be handy to be able to see it in there. Thoughts on adding it as a non-editable field? Or perhaps even with a drop-down so it can be edited from within the Edit screen?

**Comment by pippinsplugins** [comment]
I've run into this a few times.

I vote we add it, though might as well make it editable too.

**Comment by michaelbeil** [comment]
Was just gonna write up an issue for this. 🎉 👍  here.

Could be an action row instead of a drop-down. First column would be Status, then the second column would contain the action row, show a greyed out Pending status, and an Accept link is shown to the right in the row. Then deactivate or activate will show once affiliate is accepted.

**Comment by sumobi** [comment]
@AffiliateWP/core Ready for testing (I have tested). I went with a select menu, since that's what we use on the add new affiliate screen.

<img width="549" alt="screen shot 2016-12-13 at 2 04 56 pm" src="https://cloud.githubusercontent.com/assets/52581/21154660/25c1de80-c13d-11e6-8309-3f56cffc42a6.png">

<img width="550" alt="screen shot 2016-12-13 at 2 04 31 pm" src="https://cloud.githubusercontent.com/assets/52581/21154655/1aa1d294-c13d-11e6-8054-0db7146f8e3c.png">

**Comment by pippinsplugins** [comment]
@sumobi We'll need to run `affwp_set_affiliate_status()` during the update process to ensure the necessary hooks and connected actions run.

**Comment by sumobi** [comment]
@pippinsplugins Right right, otherwise the select menu will have the wrong option (will default to active) and if the admin saves an affiliate's edit screen, and that affiliate is inactive, they will suddenly become active, right?

Another way might be to detect the affiliate's current status, set that to the dropdown's default value.

**Comment by pippinsplugins** [comment]
It's not much an issue of showing the proper status; it's an issue with ensuring the proper things happen when changing the status.

For example, if I change the status from pending to active I'd expect the welcome email to get sent out.

**Comment by pippinsplugins** [comment]
@sumobi could you update this to use `affwp_set_affiliate_status()`?

**Comment by sumobi** [comment]
@pippinsplugins 

Updated it to use `affwp_set_affiliate_status()`. Issues that I can see:

1. It's updating the affiliate twice now, once for the status (if it's changed) using `affwp_set_affiliate_status()`, and once more with the existing `affiliate_wp()->affiliates->update()`. Is there a better way?

2. An email will be sent to the affiliate anytime their status is changed from `pending` to `active`. `inactive` to one of the other statuses won't fire off an email. 

    I feel like we should warn the admin about emails being sent, perhaps in the description? what do we want it to say?

3. There's still the issue of the select menu needing to show the affiliate's current status. Otherwise an admin could come to edit the affiliate, and since the select menu will just show the first option, when the edit screen is saved, the affiliate's status could change completely. I think this is next on the list before this can be completed, will hit this up soon.

**Comment by pippinsplugins** [comment]
1. That's not optimal but is okay. It's more important that the proper actions fire.

2. `Updating the status could trigger account related events, such as email notifications.`?

**Comment by pippinsplugins** [comment]
Merged!
