### ISSUE TITLE
Change visibility of log() method to public

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1968]
We should change the visibility of the `log()` method to public (currently private) in class-tracking.php. This would benefit other add-ons that need to use logging

Original discussion: https://github.com/AffiliateWP/affiliatewp-direct-link-tracking/issues/63#issuecomment-275829451

**Comment by DrewAPicture** [comment]
Rather than making the `log()` method public in this one case, I thought it might be interesting to instead look making our our logging functionality global to core, and thus accessible from anywhere. I have this working (in my testing) in PR: #1975.

If, after some more thorough testing we see some issues with accessing the `utils` property, it might be worth looking at moving instantiation of the utilities class higher in the bootstrap. This approach makes some sense anyway, especially since the nature of utilities is that they serve a utility :)

**Comment by pippinsplugins** [comment]
I like this approach at lot.

**Comment by pippinsplugins** [comment]
Merged!
