### ISSUE TITLE
WPEC: Fatal error/page not found depending on affiliate link structure

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#2077]
Affiliate links break with WP eCommerce, both pretty and non-pretty formats. The cookies store fine.

When a pretty affiliate link is used on the WP eCommerce products page it results in a 404 page. Clearing permalinks or saving the AffiliateWP settings does not fix the issue. No errors are otherwise reported.

When a non-pretty affiliate link is used on the same products page it results in the following errors and the page is not fully loaded, because of the fatal error:

```
 Trying to get property of non-object in /wp-content/plugins/wp-e-commerce/wpsc-components/theme-engine-v1/helpers/template.php on line 147
```

```
PHP Notice:  is_single was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in /wp-includes/functions.php on line 4136
```

```
PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /wp-includes/query.php:28
```

If you take away the query string (pretty or non-pretty), everything works fine. Affiliate seems to work fine on other pages.

Reported by customer initially and I've replicated the issue on 3 computers.

To replicate:

1. Install both AffiliateWP and WP eCommerce
2. Add a product and an affiliate
3. Go to the `/products-page/` and use both a pretty and non-pretty affiliate link to see the 2 issues described above.

**Comment by pippinsplugins** [comment]
Related #2078

**Comment by pippinsplugins** [comment]
This is happening due to our `rewrites()` method of `Affiliate_WP_Rewrites` class:

```php
/**
 * Registers the rewrite rules for pretty affiliate links
 *
 * This was in Affiliate_WP_Tracking until 1.7.8
 *
 * @since 1.3
 */
public function rewrites() {

	$taxonomies = get_taxonomies( array( 'public' => true, '_builtin' => false ), 'objects' );

	foreach( $taxonomies as $tax_id => $tax ) {

		$ref = affiliate_wp()->tracking->get_referral_var();
		add_rewrite_rule( $tax->rewrite['slug'] . '/(.+?)/' . $ref . '(/(.*))?/?$', 'index.php?' . $tax_id . '=$matches[1]&' . $ref . '=$matches[3]', 'top');

	}

	add_rewrite_endpoint( affiliate_wp()->tracking->get_referral_var(), EP_ALL );

}
```

Specifically, the `add_rewrite_endpoint( affiliate_wp()->tracking->get_referral_var(), EP_ALL );` call is what triggers it.

**Comment by pippinsplugins** [comment]
I _think_ this is happening due to the `wpsc_display_products()` function in WPSC not properly checking if the queried object was retrieved successfully.

When first digging into this issue I was testing with the new development version of WPSC and it does not have this problem.

@JustinSainton able to lend any feedback here?

**Comment by DrewAPicture** [comment]
#2237 fixes the non-pretty affiliate URL problem.

With that fix pretty affiliate URLs still 404 though. Investigating.

**Comment by pippinsplugins** [comment]
@DrewAPicture this fixes the fatal error for me :+1:

**Comment by DrewAPicture** [comment]
Added a PR: #2238

**Comment by pippinsplugins** [comment]
@DrewAPicture I'm still seeing a 404 on the products page with `issue/2077`.

**Comment by DrewAPicture** [comment]
@pippinsplugins You have to save the AffWP settings to flush the rewrites. I figured tying it to AffWP would be better than always adding the rule on `init`.

Also, talked to @JustinSainton and adjusted the rewrite to use the page containing the shortcode rather than assuming `products-page`. See 320fd0ed0d7abc6725dff2f962b9091d69dcc09e.

**Comment by DrewAPicture** [comment]
To expand on why I chose adding on the `affwp_pre_flush_rewrites` hook, this is because I figured we're already adding the main taxonomy-based rewrites on AffWP settings save, so adding the new one – effectively a modified version of the taxonomy one – on the same save action would be the way to go.

**Comment by DrewAPicture** [comment]
Actually, I'm gonna nix that decision altogether and move back to `init`. I just noticed that when the products page is set as the front page, you have to follow a strange order of events to get the rewrites flushed properly – let's not make it harder than necessary :-)

**Comment by pippinsplugins** [comment]
@DrewAPicture I did that but it made no difference.

The latest commits, however do appear to fix it!
