### ISSUE TITLE
Compatibility issue with "UserPro DashBoard” plugin

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2136]
When the "UserPro DashBoard” plugin is installed alongside UserPro and AffiliateWP it seems to bring down the admin and front-end of the website, at least on the customer's site I was troubleshooting. UserPro with AffiliateWP works fine. UserPro dashboard is made by the same plugin author.

The only error outputted is this:

```
PHP Notice:  Undefined index: userpro-dashboard/userpro-dashboard.php in /wp-content/plugins/userpro-dashboard/admin/updb-updates-plugin.php on line 45
```

One of the last items in the full stack trace references AffiliateWP's `AFFWP_Plugin_Updater` class:

```
set_site_transient() /wordpress/wp-content/plugins/AffiliateWP/includes/admin/AFFWP_Plugin_Updater.php:177
```

While testing locally it did break the plugins page, refusing to load anything past the AffiliateWP plugin in the list.

I tracked the issue down to this file:

`userpro-dashboard/admin/updb-updates-plugin.php`

and these lines of code:

```
if( !$userpro->verify_purchase( get_option('userpro_dashboard_code'), '13z89fdcmr2ia646kphzg3bbz0jdpdja', 'DeluxeThemes', '15375277' ) ){
    unset( $transient->response[$this->plugin_path]->package );
}
```

As soon as they are commented out everything begins to work fine locally. I also commented them out on the customer's site and it fixed the issue also.

@AffiliateWP/core Plugins are on dropbox if anyone wants to take a look.

**Comment by DrewAPicture** [comment]
Yeah, so basically the problem here is that UserPro Dashboard is assuming that the plugin path is already set in the `update_plugins` transient:
```php
    $request_args = array(
        'id' => $this->plugin_id,
        'slug' => $this->plugin_slug,
        'version' => $transient->checked[$this->plugin_path]
    );
```
When in fact, it's later initialized with `$response`:
```php
    $transient->response[$this->plugin_path] = $response;
```

The fix for this would be to additionally check if the plugin is present in the `checked` value before proceeding:
```php
    if(empty($transient->checked)) return $transient;
    if(empty($transient->checked[$this->plugin_path])) return $transient;
```

Either way, the reason WordPress is whitescreening with the UserPro Dashboard + AffWP combo is likely that the transient value overloaded in UserPro is malformed, and when AffWP calls `set_site_transient()`, it triggers the malformed overload.

**Comment by DrewAPicture** [comment]
After some discussion with @amdrew, we've determined that everything AffWP is doing in this scenario is above-board and as such the onus for avoiding the conflict falls on the developers of UserPro Dashboard to prevent issues.
