### ISSUE TITLE
Referral error being logged when no affiliate link is used, mark_referral_complete() always being fired

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2200]
A customer reported the following error message in their debug log file:

`Referral could not be retrieved during complete_referral(). Value given: xyz` 
(xyz being the order number)

https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-base.php#L166

They also mentioned they have had complaints referrals weren't being tracked properly from their affiliates.

Put the above two together and it seemed that there was some kind of issue related with referral tracking. Upon closer inspection however referral tracking worked perfectly and the error message above appeared **whenever** an order is made,  without an affiliate link or cookies present. Customer was using WooCommerce, also replicated locally with EDD. 

It seems counter-intuitive to show this message when orders without affiliate links are made and should _only_ show if AffiliateWP had trouble completing the referral.

The real issue actually seems to be that our EDD and WooCommerce integrations (and many more) run the `mark_referral_complete()` method (which in turn, runs `complete_referral()`) regardless. EDD on `edd_complete_purchase`, and WooCommerce on `woocommerce_order_status_completed` and `woocommerce_checkout_order_processed`.

I propose we only run the `mark_referral_complete()` method if the order has a referral attached to it. EDD for example provides `$payment_id` with the `edd_complete_purchase` hook so we can first check to see if there was a referral tied to the order.

@AffiliateWP/core Can anyone think of a better way?

**Comment by pippinsplugins** [comment]
The downside to checking if the referral exists before running `mark_referral_complete()` is it adds an additional query to the purchase completion process. Since orders are often completed through webhooks, we also can't use the `was_referred()` method.

**Comment by sumobi** [comment]
How much would one extra query negatively impact things? Slight millisecond delay while processing the payment? It seems like it's needed since code is being run regardless of whether an affiliate is actually being tracked.

**Comment by pippinsplugins** [comment]
On most sites? Almost nothing. The problem potentially arrises on very large sites, however, where additional queries eventually create a cascading affect that significant hurts server performance.

Is it actually likely to happen? Unsure. Is it possible? Definitely.

**Comment by DrewAPicture** [comment]
Slating this for 2.1.8. Talked about it with @amdrew and I agree that we should just bail, but we'll still need to do the query to accomplish the check.

The way it works right now, we're always registering `mark_referral_complete()` against `edd_complete_purchase` or the WC hooks, and the value passed to that (payment/order ID or referral) is checked first for empty (nothing passed), then if it's an object, we attempt to pull the referral, finally falling back to seeing if it could be a `reference` value associated with a referral in the db.

The problem arising here is essentially that something is being passed, so the first check passes. Then we check if it's an object, and if it isn't we check for a referral with that reference.

So what should be happening here is actually completely bailing under the circumstance where somethign is passed and it's both not a referral nor a valid reference. Rather than show a referral based error, at that point we should be just bailing.

**Comment by DrewAPicture** [comment]
PR: #2447

**Comment by amdrew** [comment]
@DrewAPicture 👍 Nice, that fixed it for me
