### ISSUE TITLE
Server timeout while rendering overview totals metabox

### ISSUE THREAD

**Issue by davefx** [AffiliateWP/AffiliateWP#2202]
We are experiencing a server timeout while visiting AffiliateWP Overview page.

We have narrowed the problem to the overview totals metabox.

**Comment by DrewAPicture** [comment]
I'm wary of the "freshness" of the `affwp_alltime_earnings` option value, as suggested in #2203.

Looking at the `paid_earnings()` method, I think we could probably fine-tune the `get_referrals()` query to only pull the `amount` fields instead of the full referral objects which is likely what's slowing it way down.

So when initializing the `$args` array, set `fields` to `amount`, then we can consolidate this logic and remove the list pluck because we've only retrieve the amounts based on the given args:
```php
$referrals = $this->get_referrals( $args );

$earnings  = array_sum( wp_list_pluck( $referrals, 'amount' ) );
```

**Comment by DrewAPicture** [comment]
Opened a second PR with my suggestion for refining the `paid_earnings()` query + a test: #2205

**Comment by pippinsplugins** [comment]
Works well for me and tests passed, merged!
