### ISSUE TITLE
Customer site issue with WP Simple Pro Stripe and PayPal Button integrations

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2221]
https://secure.helpscout.net/conversation/336313550/55680/?folderId=1170842

Customer has two issues on his site, neither of which I could reproduce locally or on the sandbox so I am at a loss as to next steps.  At least the first one generates an error in the debug log.

page for purchase is /Pricing

1. WP Simple Pay Pro/Stripe - referral is created but stays at Pending.  There are errors in the debug log:   

```17-5-17 17:27:57 - Visit #111 recorded for affiliate #3 in track_visit()
2017-5-17 17:31:13 - Processing referral for Stripe charge.
2017-5-17 17:31:13 - Pending Referral #5 created successfully.
2017-5-17 17:31:13 - Pending referral created successfully during insert_referral()
2017-5-17 17:31:13 - Referral could not be retrieved during complete_referral(). Value given: ch_1AKVzRGAg3BjSMN0dWnoBC4c
2017-5-17 17:31:13 - Referral failed to be set to completed with complete_referral()
```
This user has the WP Simple Pay Subscription plugin even though he does not have our Recurring Referrals add-on.  He is aware it will only generate one referral for the initial payment.  I tested this scenario in our sandbox (deactivating AffWP Recurring Referrals) and it created the referral and changed it to Unpaid without issue.

2. PayPal Buttons - A purchase using the PayPal buttons does not create a referral.  There are no entries in the debug log for any attempts, nothing.  I verified his PayPal Buttons appear to be created correctly.  I created a new page for a PayPal test button I created using my sandbox account , see the page  /paypal-testing.   The credentials for payment are:  

gingercoolidge-buyer@me.com
affwptesting
 
This worked on our sandbox /paypal site.

**Comment by pippinsplugins** [comment]
@gspice tracked it down. It was due to the Object / DB caching in W3 Total Cache.

Those caching options were preventing the referral look up (after the referral was created) from succeeding because the DB cache was not updated in time.

Disabling DB / object caching in W3 Total Cache fixes it.

Here you can see a pending referral from before the caching was disabled and an unpaid referral from immediately after disabling it:
<img width="1657" alt="screen shot 2017-05-18 at 10 10 37 am" src="https://cloud.githubusercontent.com/assets/1034109/26209410/56b5e9e2-3bb2-11e7-9fdd-e7661dd61e2a.png">

**Comment by pippinsplugins** [comment]
Same fix should apply to PayPal.

**Comment by gspice** [comment]
Follow-up note on this:  The PayPal Buttons integration not working was from two jQuery errors showing in the console.  The offending plugin was:   [Speed Booster Pack](https://wordpress.org/plugins/speed-booster-pack/)   After deactivating everything worked as expected.
