### ISSUE TITLE
Add Paid Referrals count to Referrals report screen

### ISSUE THREAD

**Issue by lisag** [AffiliateWP/AffiliateWP#2222]
@DrewAPicture I think we discussed this on Slack, but I can't find anywhere where we have logged it. Feel free to close this if it does exist elsewhere! 

I think it'd be great to add the Paid Referrals count to the Reports -> Referrals screen. Currently we have Unpaid referrals count but not Paid.

**Comment by tubiz** [comment]
PR: #2495 

We need to delete this meta field `meta-box-order_affiliates_page_affiliate-wp-reports` for all users when AffiliateWP plugin is upgraded to version 2.1.11 so to as to reset the position of the meta boxes on the reports page.

**Comment by DrewAPicture** [comment]
> We need to delete this meta field meta-box-order_affiliates_page_affiliate-wp-reports for all users when AffiliateWP plugin is upgraded to version 2.1.11 so to as to reset the position of the meta boxes on the reports page.

I think we can avoid needing to reset the user meta keys here. Even if we wanted to, there isn't really a performant way to do it short of tying a new batch process to an upgrade routine for 2.1.11. Plus, the user meta key applies to meta box tile positions for _all reports tabs_, not just this one – I would hesitate to reset all user settings just because we want a new tile to be in a specific position.

My suggestion would be to convert the existing `unpaid_referrals` tile to mimic how the `affiliate_paid_unpaid_referrals` tile works (without the part that filters by the specific affiliate, obviously), simply using a tile ID of `paid_unpaid_referrals` and keeping the context already set for the `unpaid_referrals` tile.

**Comment by tubiz** [comment]
My exact thought. I have mimicked the `affiliate_paid_unpaid_referrals` tile view instead.

![reports affiliatewp dev wordpress 1](https://user-images.githubusercontent.com/602184/34532280-02b7826a-f0cf-11e7-95a4-02d123d94939.png)
