### ISSUE TITLE
Fatal error: Cannot redeclare update_blog_status()

### ISSUE THREAD

**Issue by AiratHalitov** [AffiliateWP/AffiliateWP#2305]
I can't activate AffiliateWP v2.1 

Log:
`Fatal error: Cannot redeclare update_blog_status() (previously declared in /site_path/wp-content/plugins/buddypress/bp-core/bp-core-wpabstraction.php:185) in /site_path/wp-includes/ms-blogs.php on line 992`

BuddyPress 2.8.2
WordPress 4.8

**Comment by DrewAPicture** [comment]
Hi @AiratHalitov, thanks for the report.

Initial testing shows no problem activating either AffiliateWP 2.1 and BP 2.8.2 together. It's possible there is another plugin in play here.

Can you please create a [support ticket](https://affiliatewp.com/support/) so we can try to investigate your setup further?

**Comment by DrewAPicture** [comment]
Could be the require_once on `ms-blogs.php` in `affiliatewp_install()`, but sort of the nature of require_once is that it's only supposed to require it once. I wonder if BP is tripping over the require happening outside of core.

**Comment by DrewAPicture** [comment]
Further investigation shows that BP is deliberately declaring multisite-only functions when _not_ multisite. I'm assuming it's for similar efficiency to what we're doing – using multisite functions regardless of whether the site is on multisite.

**Comment by DrewAPicture** [comment]
Talked with @jjj, and i think we're probably going to need to move toward abstracting the actual business logic out to a separate function, then rather than manually loading the ms-bootstrap, only run multisite-specific stuff if _actually multisite_.

Milestoned this for 2.1.1 and working on a PR.

**Comment by DrewAPicture** [comment]
PR: #2306

**Comment by pippinsplugins** [comment]
Just had another report of this. Merging, closing, and deploying update.

**Comment by JJJ** [comment]
For context, the abstraction layer that's in BuddyPress originally also pulled in `ms-blogs.php`, but we were forced to write our own abstraction when we decided to support single-site, because this file didn't exist in single-site installs before WordPress 3.0.

The only other approach I could think for y'all to take would be to override & defer the action BuddyPress loads on to make it happen after AffiliateWP. Or, we could explore manually `include_once` the core file the way y'all did.
