### ISSUE TITLE
Latest version of WP Simple Pay does not use Stripe_Checkout class

### ISSUE THREAD

**Issue by edwinbsmith** [AffiliateWP/AffiliateWP#2396]
The commit at [0a3ec61](https://github.com/AffiliateWP/AffiliateWP/commit/0a3ec6168b1406bbf1402185eff99a8471b572be) is requesting a class that does not exist in the latest version of WP Simple Pay (and WP Simple Pay Pro) at this link: https://wpsimplepay.com/

**Comment by amdrew** [comment]
Thanks @edwinbsmith!

@DrewAPicture Could you please take a look? I upgraded to the latest version of their free version (https://wordpress.org/plugins/stripe/) and it does indeed look like things have changed. The `Stripe_Checkout` class we check for (https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-stripe.php#L184-L186) is now located at `Stripe/includes/old/class-stripe-checkout-shared.php`

@gspice Sounds like your ticket is related to this issue. The customer is using WP Simple Pay Pro v 3.1.5. The integration class won't be loading at all.
https://secure.helpscout.net/conversation/438717759/67397/?folderId=205531

**Comment by amdrew** [comment]
It seems our integration class **is** actually being loaded ok since the `Stripe_Checkout` class still exists inside WP Simple Pay (at least in the free version). 

Going to dig into the customer ticket and see why their referrals aren't being created and if it's related to this issue.

**Comment by amdrew** [comment]
Ok, got a hold of the pro version and v3 does not have a `Stripe_Checkout_Pro` class as @edwinbsmith mentioned. The free version seems fine however. We'll need to update our integration to support v3 (pro) by modifying the conditional to allow the integration class to run.

The plugin is also renamed, and it looks like v2 may still be offered since the plugin name is now `WP Simple Pay Pro 3` (v3) vs `WP Simple Pay Pro for Stripe` (v2).

**Comment by amdrew** [comment]
PR https://github.com/AffiliateWP/AffiliateWP/pull/2397

Tested and referrals now work fine with v3 (support ticket is related after all).

**Comment by gspice** [comment]
@amdrew This appears broken again :-(     Can you help me test this please?  I've setup the latest WP Simple Pay plugin (3.1.6) on the sandbox and it is not creating referrals.   The one we test with above was 3.1.5 I believe.      

http://s14890.p27.sites.pressdns.com/stripe

**Comment by amdrew** [comment]
@gspice Replicated. We were rather unlucky on this one. The namespace in v3.1.6 (which came out ~2 days or less ago) changed from v3.1.5 so the integration code isn't running again.

**Comment by amdrew** [comment]
@DrewAPicture PR: https://github.com/AffiliateWP/AffiliateWP/pull/2398

**Comment by pippinsplugins** [comment]
@amdrew @DrewAPicture please go ahead and push this release out first thing tomorrow morning.

**Comment by nickyoung87** [comment]
@pippinsplugins @amdrew @gspice 

I am a developer for WP Simple Pay. Sorry! Didn't take into consideration a few of the integrations others have made to work with our plugin. Fortunately it's all done and we shouldn't be changing anything so heavily for the foreseeable future. 

Glad you guys were able to iron this one out quickly.

**Comment by pippinsplugins** [comment]
@nickyoung87 No worries, it happens. Obviously we hope it doesn't again :) Thanks!

**Comment by nickyoung87** [comment]
You might be able to replace this with just one line now:

`$key = simpay_get_secret_key();`

That new function will just return the correct key based on the live or test mode check automatically so you don't have to check for it yourself.

**Comment by gspice** [comment]
I've verified AffiliateWP v2.1.5.2 and WP Simple Pay Pro 3 v3.1.6 on single payments creates a referral as expected.   I'll dig in to testing subscriptions next.

**Comment by pippinsplugins** [comment]
@nickyoung87 could you guys make the old methods work please? We can change them if so but the fact that the update broke two different integrations should be evidence that those old methods need to be maintained.

**Comment by nickyoung87** [comment]
@pippinsplugins Let me talk with Phil and see what we can do. 

The problem though is that the plugin was completely restructured and rewritten from scratch.

I do agree with you that this is bad that the integrations got broken, however, we also only have very few integrations to start. Going forward we will not be changing any of the new stuff that is currently in place and if we do we will be making sure to keep any deprecated functions around as we now have the base structure we will likely be using for years to come.

Sorry about all of this, let me get back to you on our plan of action.

Is it just these 2 integrations you have that work with us, or are there more that I might not know about?

**Comment by pippinsplugins** [comment]
@nickyoung87 just these two.

If you could let me know if you decide to support the old methods or not to support them, that would be great. We'll wait to fix our other integration until we hear from you.

**Comment by nickyoung87** [comment]
@pippinsplugins Alright so we discussed this at length and came to a conclusion. We think it would be better if we don't add support for these older functions. 

Our main reasoning behind this is that the code for the old version of the plugin and the new version is so different that it would be quite difficult to cover everything that is possible. We also are done with our code restructuring for both the Lite version and Simple Pay Pro 3 so going forward there should not be any unexpected changes as this one was. Also, with the new code structure it will be easier for us to add deprecated functions if needed going forward rather than trying to make functions work backwards compatible from the old system we had in place.

I am very sorry for this huge inconvenience. I would like to offer myself a personal helping hand in my free time to get you guys going with this integration. It is my number one priority to help you guys with anything you need for this and I will jump on any of it right away until you have a release ready version.

We do still support SP 2.x for the time being so I can help with sorting out how you can check for that vs SP 3 and the related functions to make everything work the same as before.

You can also email me directly at mycorpweb AT gmail if we need to hash out some things further that aren't necessary on this GH issue.

Again, I really apologize for the unexpected events but please let me know what I can do to help and where I can start.

**Comment by pippinsplugins** [comment]
Ok, we'll make due.
