### ISSUE TITLE
Affiliate registration form not submitting correctly

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2410]
After submitting the affiliate registration form after logging in from the affiliate area's login form, the registration form shows again, instead of actually registering the affiliate.

Steps to replicate:

1. Create a new user account (or use an existing one)
2. In another browser, log in as the new user using the login form on the `/affiliate-area` page.
3. Immediately on the next screen, submit the affiliate registration form.

Expected outcome: 

The affiliate area should be shown since the user has just registered as an affiliate. Or, if affiliate approval is enabled, a "pending" notice should be shown to the newly registered affiliate.

Actual result:

The affiliate registration form is shown again.

Notes:

- Submitting it the affiliate registration form the second time works. It only gets "stuck" the first time.
- Logging in via _first_ the WordPress login page, then navigating to the affiliate-area page and submitting the form works.
- Logging in via _first_ the WooCommerce `my-account` page, then navigating to the affiliate-area page and submitting the form works.

Seems to only be an issue when first logging in via AffiliateWP's login form.

**Comment by amdrew** [comment]
Looks like the issue is somehow related to the login form that is shown with the affiliate registration form. For example, here's a workaround that works perfectly fine.

1. Place the standalone [affiliate_login] shortcode underneath the [affiliate_area] shortcode. The Affiliate Area page now look like this:

    `[affiliate_area]`

    `[affiliate_login]`

2.  Set the "Affiliate Area Forms" admin option to "Affiliate Registration Form Only" to disable the login form from the `[affiliate_area]` shortcode.

3. Page now looks the same as it did before, except logging in from the [affiliate_login] form and then submitting the affiliate registration works correctly.

**Comment by gspice** [comment]
@amdrew Wondering if the issue on this ticket is the same?
https://secure.helpscout.net/conversation/452904513/68889?folderId=1170842

Sometimes after populating all of the fields, the registration form comes back blank, and the registration does not take place.  In my local testing (and on the user's site)  I have reproduced this, however, not consistently.  

I reproduced it when I put an invalid URL in the Website URL field  (which is what the user did on one of her tests). The first time I did it on my local site I received an error upon submission (which is correct, expected behavior):

![valid-website-url](https://user-images.githubusercontent.com/3018245/32068218-870a130a-ba3a-11e7-90eb-041cd49a4efb.png)

After that, I was able to enter the same, malformed URL and it would append a .com to it and create the registration anyway.  I'm stalled on how to consistently reproduce this.

**Comment by amdrew** [comment]
@gspice Sounds like it could be related for sure

**Comment by pippinsplugins** [comment]
PR ready for testing that fixes it.

Problem was due to the redirect parameter being empty.

**Comment by amdrew** [comment]
@pippinsplugins Fixes it for me 👍 

@gspice Could you also test please?

**Comment by gspice** [comment]
@amdrew @pippinsplugins 

Works successfully for me!  Tested on two separate sites using the original values from the support ticket I mentioned above.
