### ISSUE TITLE
Visits graph shows incorrect totals when filtered by an affiliate

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2450]
PR: #2456

Reported on this ticket:
https://secure.helpscout.net/conversation/463865185/70033?folderId=1170842

When you view the Visits graph for an affiliate, the numbers on the graph are incorrect.  The all time visits (as of today) were 70, but the graph shows 2563 unconverted and 186 converted when hovering over the graph point.  

<img width="1372" alt="affiliate-visits-graph" src="https://user-images.githubusercontent.com/3018245/32581243-46d9e622-c4a6-11e7-9a04-63c4e36dd49d.png">

**Comment by DrewAPicture** [comment]
After some investigation, it looks like the root of the problem lies in query for date-based objects throughout core without first converting dates to UTC (essentially, we're currently querying based on "now" dates instead of first accounting for the GTM offset in incomine date values). This appears to be widespread and reaches further than just visit queries. Working on a PR + tests.

**Comment by DrewAPicture** [comment]
Started a WIP PR: #2454

**Comment by DrewAPicture** [comment]
Closed #2454 and started a new WIP PR with a different approach: #2456

**Comment by DrewAPicture** [comment]
The attached PR, #2456 is ready for testing and review:

@gspice @amdrew 

Testers:

The primary things to test with this PR are the following:
1. Filtering reports by specific dates or "today" should reflect expected results
2. Any dates and times showing in AffWP admin screens should now be displaying in a nicer format and in "WordPress time" – that is, respecting the WordPress timezone settings for display. If you haven't yet set the Timezone for your test site in General > Settings, you should do that.

The primary bug the PR fixes is that reports weren't always reflecting objects created for the time period being filtered for. It turns out that this was because we weren't translating dates/date ranges entered in the UI into UTC times to ensure that objects returned matched those dates. We store the dates/times in database in UTC (GMT+0) to ensure a "neutral" time scheme, this allows the site to adjust the timezone as needed without screwing up the actual data that's being stored.

The PR not only fixes querying for objects with WordPress dates/times to return UTC-date/time-based results, but adjusting all admin and template views to display dates/times in "local" or "WordPress" time.

For example, let's say you have a referral created at 23:00 UTC, if your Timezone is set to Denver (-7), the time would be _displayed_ as 4:00 pm. An easy way to confirm times and dates are showing in "WordPress time" is to retrieve the object you're checking in the command line first:

![Visit get](https://cl.ly/43381S3G0l2u/Screen%20Shot%202017-11-17%20at%206.39.43%20AM.png)

Then compare that to what's displayed in the admin:

![Visit](https://cl.ly/0N0f3w352o3B/Screen%20Shot%202017-11-17%20at%206.38.42%20AM.png)

Note: I suggest using the [affiliatewp-wp-cli-generator](https://github.com/AffiliateWP/affiliatewp-wp-cli-generator) plugin to generate test objects for filtering by "Today" in reports. For help on accepted parameters, just replace "wp" in the command with "wp help", e.g. `wp affwp affiliate generate` would become `wp help affwp affiliate generate`:

![Generate](https://cl.ly/0s3o2p0r0h3S/Screen%20Shot%202017-11-17%20at%206.41.58%20AM.png)

![Visit report](https://cl.ly/283O441J230B/Screen%20Shot%202017-11-17%20at%206.43.06%20AM.png)

**Comment by DrewAPicture** [comment]
@pippinsplugins @amdrew 

On the technical side, there are a few developer notes:

* This PR introduces pieces of the PR attached to #773, but without the actual integration of the `Carbon` library. Taking this approach will allow us to much more easily integrate with Carbon in 2.2 for simplifying the date filtering code for reports and other screens.

The PR introduces some new functions, methods and a class, notably:
* `affiliate_wp()->utils->date()` which instantiates a new `\AffWP\Utils\Date` object with the WordPress timezone applied to the actual date string contained inside it. See notes below for caveats on "WordPress time" conversion.
* `affiliate_wp()->utils->date_format`, `affiliate_wp()->utils->time_format`, and `affiliate_wp()->utils->wp_offset` – Three read-only properties have been added to the utilities class for easy access. Their values are derived from core options and allow us to pull them once at run-time instead of every time we need to format a date in "WordPress time".
* `affwp_date_i18n()` – serves as a wrapper for `date_i18n()`, but adds the ability to use short-hand date formats (more on that below). Note that the arguments are reversed.
* `[Object]->date()` and `[Object]->date_i18n()` for more easily formatting core object dates in "WordPress time" (more below)

The `Date` object instantiated by `affiliate_wp()->utils->date()` extends PHP's `DateTime` class, which brings a lot of power to the table in terms of formatting. It also brings built-in methods like `getTimestamp()`. By extending `DateTime`, this gives us the flexibility to squeeze our own functionality in between, such as a new `getWPTimestamp()`, and our own version of the `format()` method, which gives us the flexibility to support "short-hand" formats before passing things off to the parent class.

Note that while the date/time in the `Date` object is automatically converted to "WordPress time", the actual timestamp of the `Date` object still represents the UTC date. To get the timestamp representative of "WordPress time" use `affiliate_wp()->utils->date()->format( 'wp_timestamp' )`, or if you already have a `Date` object instantiated, you can use `$date->getWPTimestamp()`.

The `$date->format()` method accepts a variety of "short-hand" formats for ease of use, including:
* 'date' (value of the `date_format` option)
* 'time' (value of the `time_format` option)
* 'datetime' (values of `date_format` and `time_format` combined)
* 'mysql' (`Y-m-d H:i:s` format)
* 'timestamp' (retrieves the unchanged/UTC timestamp)
* 'wp_timestamp' (retrieves the timestamp based on the converted date)

If you want to instantiate a `AffWP\Utils\Date` object directly, you can, but you'll need to do it the way `DateTime` expects, with a `DateTimeZone` object passed as the second parameter. A new `affwp_get_timezone()` function makes this easier:
```php
$date = new \AffWP\Utils\Date( 'today', new \DateTimeZone( affwp_get_timezone() ) );
echo $date->format( 'mysql' );
```

Additionally, the PR introduces two new helper methods for core objects, `date()` and `date_i18n()`. These helpers work the same way as `affiliate_wp()->utils->date()`, but are accessible directly at the object level, which allows us to _much_ more easily format object dates, e.g.
```php
$referral = affwp_get_referral( $referral_id );
echo $referral->date_i18n( 'datetime' );
```
See the theme and admin template changes in the PR for how that helps us simplify formatting dates.

**Comment by gspice** [comment]
Works great!  
*All points on the graph showed correct totals and counts for the date range selected.
*New visits and referrals now reflect my correct time zone settings in WordPress.

**Comment by pippinsplugins** [comment]
This is working great for me @DrewAPicture, nice work!
