### ISSUE TITLE
Update iThemes Exchange to ExchangeWP

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2504]
iThemes Exchange is now https://exchangewp.com

We need to update our integration to reflect this change.

@tubiz Could you tackle this for 2.1.11?

**Comment by pippinsplugins** [comment]
Moved to 2.1.12.

**Comment by tubiz** [comment]
@amdrew Yes, I will tackle it for 2.1.12. But I will need a copy of the plugin.

**Comment by amdrew** [comment]
@tubiz 👍 We're working on getting a copy.

**Comment by amdrew** [comment]
@tubiz Sent you an email with a link to ExhangeWP

**Comment by tubiz** [comment]
@amdrew I got the email. Thanks.

**Comment by tubiz** [comment]
I noticed that different gateways have different order status for successful transactions, due to this some referrals are not marked as `rejected` if they are `cancelled`, `refunded` or `voided`. 
This is also fixed in the PR

### Payment Gateway Order Statuses 
- If PayPal is used the order status is set to `Completed`
- If Stripe is used the order status is set to `succeeded`
- If Offline Payments is used the order status is set to `paid`
