### ISSUE TITLE
WooCommerce integration updating referral right after creating it

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2556]
The WooCommerce integration is creating the initial referral and then instantly updating it.

```
2018-2-05 22:40:26 - Referral #102 created successfully.
2018-2-05 22:40:26 - WooCommerce Referral #102 updated successfully.
```

As a result, the `affwp_insert_pending_referral` filter is rendered useless since anything filtered is overridden:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-woocommerce.php#L204

**Comment by pippinsplugins** [comment]
@tubiz could you look into this?

**Comment by tubiz** [comment]
@pippinsplugins will do.

**Comment by tubiz** [comment]
@pippinsplugins @amdrew Presently the pending referral is created in the WooCommerce integration using either of the `woocommerce_checkout_order_processed` and `woocommerce_checkout_update_order_meta` hooks.

The `woocommerce_checkout_update_order_meta` hook was added due to referral not created when Apple Pay is used #2363.

The `woocommerce_checkout_update_order_meta` hook is fired first in WooCommerce before the `woocommerce_checkout_order_processed` is then fired, so the pending referral is always created using `woocommerce_checkout_update_order_meta` hook.  The pending referral that was created is then updated immediately due to the `woocommerce_checkout_order_processed` hook being called again to create a new referral.

I will suggest we create the pending referral using the `woocommerce_checkout_update_order_meta` hook since it works for Apple Pay and any other payment method and remove the `woocommerce_checkout_order_processed` hook. Also the check below will have to be removed as well

```
if( doing_action( 'woocommerce_checkout_update_order_meta' ) && did_action( 'woocommerce_checkout_order_processed' ) ) {

	// woocommerce_checkout_order_processed does not fire during Apple Pay processing. If it has fired, this is not an Apple Pay purchase and we need to bail
	if ( 'stripe' === ( version_compare( WC_VERSION, '3.0.0', '<' ) ? $this->order->payment_method : $this->order->get_payment_method() ) ) {
		return;
	}

}
```

Another option is to add this check before a pending referral is created and still leave the  `woocommerce_checkout_order_processed` and `woocommerce_checkout_update_order_meta` hooks but I am unable to test this with Apple Pay

```
// Prevent the referral from being updated immediately it is created
if( doing_action( 'woocommerce_checkout_order_processed' ) && did_action( 'woocommerce_checkout_update_order_meta' ) ) {
	return;
}
```

**Comment by pippinsplugins** [comment]
@tubiz your first suggestion sounds like a good approach.

**Comment by tubiz** [comment]
@pippinsplugins ok. I will submit a PR for it.

**Comment by tubiz** [comment]
PR: #2582 

Please test that referral is still being created if Apple Pay is used.

**Comment by amdrew** [comment]
@gspice Can you please test Apple Pay?

**Comment by gspice** [comment]
Works perfectly! 

![woo-order-payment](https://user-images.githubusercontent.com/3018245/36501748-ca896daa-16fc-11e8-9c62-5705fa3bb988.png)

![woo-order-notes](https://user-images.githubusercontent.com/3018245/36501755-ce05db9e-16fc-11e8-994e-f76bc8c752fa.png)

**Comment by amdrew** [comment]
Normal referral works for me, only one reference to the referral (#140 below) being created, perfecto. #139 was before testing the PR.

<img width="538" alt="screen shot 2018-02-22 at 12 25 45 pm" src="https://user-images.githubusercontent.com/52581/36511444-87aa3be8-17cb-11e8-8b94-e7a7210f097b.png">

**Comment by pippinsplugins** [comment]
@amdrew so good to merge?

**Comment by amdrew** [comment]
@pippinsplugins Yep, apply pay still works, normal referrals work (and not updated after being created), we're good here.
