### ISSUE TITLE
Two referrals are generated when the MemberMouse integration is enabled

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2557]
>During my tests, I can see that referrals are created properly, but for each successful referral, I am also getting a 0 amount referral for the Default Membership.

![screen shot on 2018-02-06 at 17_12_16](https://user-images.githubusercontent.com/4752949/35870140-294b0288-0b61-11e8-8721-bd114867f504.png) 

Ticket: https://secure.helpscout.net/conversation/519237159/75619?folderId=634609.

**Comment by amdrew** [comment]
@michaelbeil I'm working on getting access to our membermouse site. In the meantime, have you tried to replicate the issue by following the customer's exact set up on our testing site?

Perhaps it's related to the fact that it's a bundle, with 2 products inside. E.g. Click the `Bought in` link, under `Associated Access` on the `Bought In` row:

<img width="1595" alt="screen shot 2018-02-08 at 3 23 38 pm" src="https://user-images.githubusercontent.com/52581/35952312-4967911a-0ce4-11e8-8303-ddaf3b5882e2.png">

Bundle has 2 products inside:

<img width="679" alt="screen shot 2018-02-08 at 3 23 50 pm" src="https://user-images.githubusercontent.com/52581/35952311-493b5c80-0ce4-11e8-80a3-230ff7f1ba2a.png">

Perhaps that's why it's generating 2 referrals. Can you confirm?

**Comment by michaelbeil** [comment]
I’ve been able to replicate the $0 generated referral, but not 2 referrals. I will create a bundle product and attempt to replicate this.

**Comment by michaelbeil** [comment]
I created a test bundle, however no referrals are created: http://beil.io/o4I7mR.

**Comment by amdrew** [comment]
Replicated the issue on our test site:

<img width="1152" alt="screen shot 2018-02-09 at 10 25 43 am" src="https://user-images.githubusercontent.com/52581/35999137-a361382a-0d83-11e8-9049-e3996ab09de9.png">

**Comment by amdrew** [comment]
I'm not sure this could be considered a bug. The obvious "fix" for this is to enable the `Ignore Referrals with Zero Amount` option in Settings -> Misc.

Here's 2 separate orders. `1503` has the option enabled to ignore the 0.00 referral.

<img width="1151" alt="screen shot 2018-02-09 at 10 43 19 am" src="https://user-images.githubusercontent.com/52581/35999885-1b34fa7e-0d86-11e8-8aea-26707db24c19.png">

**Comment by amdrew** [comment]
There does seem to be a bug however. Note that the `The Herbal Hub Membership` membership is free:

<img width="654" alt="screen shot 2018-02-09 at 10 45 39 am" src="https://user-images.githubusercontent.com/52581/36000004-79e9d0c6-0d86-11e8-9118-243126944caa.png">

The `add_referral_on_free` method should be skipping the referral as per:

https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-membermouse.php#L22-L26

Instead it's continuing on and creating that pending $0.00 referral:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-membermouse.php#L36-L39

**Comment by amdrew** [comment]
Actually, looking at this more, it seems like this is the issue:
https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-membermouse.php#L22-L27

``` php
if( ! $membership->isFree() ) {
    $this->log( 'Referral not created because membership is free.' );
    return;	
}
```

If the membership is free, shouldn't it be returning as per the `Referral not created because membership is free.'` message?

Since the membership _is_ free, it's skipping over the conditional and creating the pending $0.00 referral.

**Comment by amdrew** [comment]
Got my wires crossed. The method is called `add_referral_on_free` so it's doing exactly as it is supposed to (create a pending $0.00 referral). The conditional above is for memberships that are **not** free, so it should return and not create a referral for paid memberships.

Unless anyone disagrees, there's no bug here.

**Comment by michaelbeil** [comment]
That seems perfectly reasonable to me. I think we can close this out.
