### ISSUE TITLE
How to format(wrap) the HTML code generated by the creative shortcode

### ISSUE THREAD

**Issue by jessdaddy** [AffiliateWP/AffiliateWP#2575]
Hi. I would like to ask. How can you format the affiliate code generated by the [affiliate_creative id="1"] shortcode so that it wraps the way it does when you use [affiliate_creatives]? [affiliate_creatives] wraps the affiliate link code all pretty like. [affiliate_creative_ad="1"] on the other hand, creates a single, long line of code that needs a scrollbar. What's the fix? Thanks.

**Comment by amdrew** [comment]
Thanks @jessdaddy, it does look like there's an issue we can fix here.

@AffiliateWP/core Here's some screenshots showing the Twenty Sixteen and Twenty Seventeen theme:

## Twenty Sixteen

#### Affiliate Area:

<img width="839" alt="screen shot 2018-02-19 at 6 34 57 pm" src="https://user-images.githubusercontent.com/52581/36363669-a87912ec-15a3-11e8-9293-34d024ee281e.png">

___

#### Using the `[affiliate_creative id="1"]` shortcode. This looks fine:

<img width="726" alt="screen shot 2018-02-19 at 6 35 09 pm" src="https://user-images.githubusercontent.com/52581/36363668-a84db2c8-15a3-11e8-86b3-373012965601.png">



## Twenty Seventeen

#### Affiliate Area:

<img width="582" alt="screen shot 2018-02-19 at 6 35 51 pm" src="https://user-images.githubusercontent.com/52581/36363680-bb6c592c-15a3-11e8-9f7a-97a81bbb9cb6.png">

___

#### Using the `[affiliate_creative id="1"]` shortcode. Here we can see the issue:

<img width="571" alt="screen shot 2018-02-19 at 6 30 30 pm" src="https://user-images.githubusercontent.com/52581/36363674-b10a23a6-15a3-11e8-8bea-a2ce41c2a967.png">

___

We use the `#affwp-affiliate-dashboard-creatives` selector to apply styles to the `pre` and `code` tags, however for a single creative it needs to use `.affwp-creative`. Since the creatives in the affiliate area also use the `.affwp-creative` class we can simply use that instead.

**Comment by amdrew** [comment]
PR: https://github.com/AffiliateWP/AffiliateWP/pull/2576

@gspice @michaelbeil Could you please test this?

Here's the Twenty Seventeen theme after the PR:

___

Affiliate Area:

<img width="568" alt="screen shot 2018-02-19 at 6 44 27 pm" src="https://user-images.githubusercontent.com/52581/36363962-0fcd3106-15a6-11e8-809b-8bfa5274f638.png">

___

Shortcode:


<img width="556" alt="screen shot 2018-02-19 at 6 44 36 pm" src="https://user-images.githubusercontent.com/52581/36363959-0fa3485a-15a6-11e8-9e4c-0b970568204a.png">

**Comment by gspice** [comment]
Tested -- successfully wraps for me when using the shortcode.

**Comment by jessdaddy** [comment]
@amdrew perfect. thanks
