### ISSUE TITLE
Ninja Forms integration - referral description is blank

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2589]
When a referral is created from a Ninja Form submission, the description of the referral is blank.  It used to show the form title as the referral description if I remember correctly.   It doesn't matter if it's a product form or a zero-amount form:

![form-referrals](https://user-images.githubusercontent.com/3018245/36693144-2d5f7de8-1aef-11e8-98c0-1aa49e2dc154.png)

AffiliateWP: 2.1.15
Ninja Forms:  3.2.14

**Comment by amdrew** [comment]
@gspice Yeah, pre 3.0 it showed the form title. From v3.0 onwards, you have to manually enter the description otherwise it will be blank:

> In the Description field, enter some text that clearly describes where the referral came from, such as “My Contact Form” or “My First Product”, etc.

https://docs.affiliatewp.com/article/76-ninja-forms

I mentioned the same thing here:
https://github.com/AffiliateWP/AffiliateWP/issues/1106#issuecomment-191584620

> If you don't specify a description under the advanced section of the add referral action, the referral comes through with a blank description. This should default to the form title as before.

There was some other discussion on the issue, but basically: 

> You can enable Merge Tags for the description, like the total and email settings. 

https://github.com/AffiliateWP/AffiliateWP/issues/1106#issuecomment-232772879

So I think that's where it ended.

I see no reason why the form title could not be used so I vote we try and implement it as a fallback, for when a description is not entered in the form settings. If the form has one or more product fields then we could also use those instead to build out the description.

**Comment by pippinsplugins** [comment]
@tubiz up for tackling this?

**Comment by tubiz** [comment]
@pippinsplugins 👍

**Comment by tubiz** [comment]
PR: #2593 

If the the form has one or more product fields that will be used to build out the description.

**Comment by pippinsplugins** [comment]
@michaelbeil @gspice ready for testing.

**Comment by gspice** [comment]
Tested successfully:  
Worked with custom description and form title if no description populated.

**Comment by michaelbeil** [comment]
Works perfectly for me whether I have a description set or a form title set without a description.
