### ISSUE TITLE
Lost My Password link goes to a different URL

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2607]
>When a user is trying to use the "Lost My Password" link on the affiliate area, the hyperlink is going to the wrong page. 

>The link is pointing to /my-account/lost-password/ 

The lost my password link we use is connected with WordPress: /wp-login.php?action=lostpassword. When WooCommerce is installed, the link is forwarded to the WooCommerce lost password link. We should change this in a future version.

Ticket: https://secure.helpscout.net/conversation/541709089/78183?folderId=205524.

**Comment by amdrew** [comment]
@michaelbeil Are you proposing we detect if WooCommerce is activated and then change the link back to what it was previously, `/wp-login.php?action=lostpassword`?

We use the `wp_lostpassword_url()` function provided by WordPress which WooCommerce is using to filter the URL. Since WooCommerce is changing the URL of all lost password links on a site, I don't think we should try to override it again, that's not really our place to do that.

Take the `wp-login.php` page for example. The `Lost your password?` link there will also link to WooCommerce's `/my-account/lost-password/` page.

**Comment by michaelbeil** [comment]
That makes sense to me.
