### ISSUE TITLE
GDPR: Include affiliate data in a user's export

### ISSUE THREAD

**Issue by DavidAnderson684** [AffiliateWP/AffiliateWP#2660]
I only see one issue here in Gitlab that mentions the GDPR (https://github.com/AffiliateWP/AffiliateWP/issues/2637), and nothing else of relevance on the commit log. So, I think at least the following issues need a resolution before a website owner using Affiiate-WP can be GDPR-compliant:

- All data stored by Affiliate WP that is linked to an identifiable user that is not already included (i.e. stuff that's not in the usermeta table, I think) needs to be included in that user's 'export' report using the new export tools in WP 4.9.6 (https://make.wordpress.org/core/2018/05/03/wordpress-4-9-6-beta/)

- Similarly for the new delete tool, a user's data should be deleted

**Comment by pippinsplugins** [comment]
I'm going to be working on this soon and will try to have it completed before the deadline.

**Comment by pippinsplugins** [comment]
First pass at this is complete. The personal data export will now include an `Affiliate Record` if there is one:
![image](https://user-images.githubusercontent.com/1034109/39791933-cacdd740-5303-11e8-8b4e-f2c7938ce337.png)

**Comment by pippinsplugins** [comment]
I've also added an export for the (new in 2.2) customer records.

**Comment by pippinsplugins** [comment]
@amdrew @DrewAPicture could I get your reviews on this please?

Note: this depends on WP nightly builds.

You need to test both the personal data exporter and the personal data eraser.

**Comment by DrewAPicture** [comment]
Tested both and they work well and display our strings.

Note: I moved the class file to includes/admin/utilities and renamed it to `AffWP\Utils\Privacy_Tools`, an now it's instantiated via `Affiliate_WP_Utilities` instead of the main bootstrap. This is mostly because it's very much a utility class and I think we should treat it as such rather than giving it first-class instantiation via the main bootstrap ;)

**Comment by amdrew** [comment]
@pippinsplugins On my export file I see a blank value for payment email and name since those were not entered. I also see just an `Affiliate Customer Record` heading.

<img width="917" alt="screen shot 2018-05-10 at 11 41 02 am" src="https://user-images.githubusercontent.com/52581/39845097-f2af0e06-5447-11e8-9bc8-c40a6bf6619d.png">

I'm not too familiar with GDPR, but how about we hide any row or section that does not hold data about the user? As a user I might perceive this as a bug. I download my file, can see the site stored my payment email and name but I can't see them. When really it's because I just didn't fill in that information.

**Comment by amdrew** [comment]
Other than that, both exporting and deleting works well! 👍

**Comment by pippinsplugins** [comment]
So far I haven't found a way to hide a section that doesn't have data. Doing so results in the WP core export process erring.

**Comment by pippinsplugins** [comment]
I've updated this to show a `No records found` message when there is no relevant data.
<img width="1072" alt="screen shot 2018-05-14 at 9 41 46 am" src="https://user-images.githubusercontent.com/1034109/40004348-20d5bbf2-575b-11e8-85c9-fe79eee46350.png">
