### ISSUE TITLE
Zippy Courses is not generating a referral

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2686]
Here are the steps that are taken:

1. https://test.com/product/test-product/offer/affiliate/
2. click buy now
3. select pay with cc option
4. pay with cc
5. return to thank you page: https://test.com/thank-you/?amt=1.00&cc=USD&cm=VM8joOnm&item_name=Test%20Product&st=Completed&tx=83M54939RA9568042
6. at this point I stopped because I saw the same error in the debug log
  
Zippy courses allows a user to purchase a course before being a member, which is going to be the dominate scenario for most sites. There are two methods for postponing registration while reserving the claim to a purchased product:

1) After purchasing, they are redirected to the site with a url similar to:
https://test.com/thank-you/?amt=1.00&cc=USD&cm=VM8joOnm&item_name=Test%20Product&st=Completed&tx=83M54939RA9568042 

Which breaks down as:
{
"amt": 1,
"cc": "USD",
"cm": "VM8joOnm",
"item_name": "Test Product",
"st": "Completed",
"tx": "83M54939RA9568042"
}

2) in the confirmation email sent to the associated paypal email, there is a url to claim your purchase, here is the url for the test purchase: https://test.com/login/?claim=VM8joOnm

It looks like AffiliateWP is attempting to assign the purchase to the affiliate at the time of purchase, before the user has been created. This entry is in the debug log:

```
2018-5-24 13:42:17 - Visit #14 recorded for affiliate #4 in track_visit()
2018-5-24 13:53:46 - Arguments being sent to DB: array (
'amount' => '0.5',
'reference' => 1256,
'description' => 'Test Product',
'campaign' => '',
'affiliate_id' => 0,
'visit_id' => false,
'products' => 'a:1:{i:0;s:3:"306";}',
'custom' => '',
'type' => 'sale',
'context' => 'zippycourses',
'customer' =>
array (
'first_name' => '',
'last_name' => '',
'email' => 'cshanejennings@gmail.com',
'user_id' => 0,
'ip' => '173.0.81.1',
'affiliate_id' => 0,
),
)
2018-5-24 13:53:46 - Pending referral could not be created due to an error.

```

It appears like the user_id is 0 in this case because the user hasn't been
created. The referral should be generated after the sale has gone through.  

Screenshot of browser cookies: http://beil.io/0Ocepu.

User stated: 
>I'm available to assist if that would be helpful. I'm in a super rush to get this done and happy to help however I can. 

Ticket: https://secure.helpscout.net/conversation/586527777/82718?folderId=634609.

**Comment by cshanejennings** [comment]
@pippinsplugins - This is being used on subdomain of a multisite instance. I only saw a change in the cookies for the parent site and saw no change in the subdomain's cookies since the first visit.  It's possible they could be happening here.

The failure seems to happen here: https://github.com/AffiliateWP/AffiliateWP/blob/80501b5e36af35d18a00e48c84f391ae34b50a37/includes/integrations/class-base.php

around line 154 inside the insert_pending_referral function.

Which is called from: https://github.com/AffiliateWP/AffiliateWP/blob/80501b5e36af35d18a00e48c84f391ae34b50a37/includes/integrations/class-zippycourses.php

inside add_pending_referral around line 185, which... judging by the comment: "Store a pending referral when a new order is created", looks like it stores the data with a user ID of whatever is available at the time.  I don't see any hooks that seem to be related to user registration, so I don't think there are any other opportunities to assign the conversion, so it remains in purgatory.

I reached out to James Kinney at Zippy Courses to see if he has any insight.  I'm happy to help any way I can.

**Comment by cshanejennings** [comment]
UPDATE:  I followed the instructions here: https://docs.affiliatewp.com/article/138-will-affiliatewp-work-on-a-multisite-installation and added the wp-config flag, flushed all site and local caches and re-ran the test with the same error in the debug log as above.  but... the cookie now shows entries for AffiliateWP:

![updated cookies](https://user-images.githubusercontent.com/547913/40500641-5f0c13bc-5f53-11e8-9fd7-6cb5e3fe76bd.jpg)

**Comment by pippinsplugins** [comment]
@tubiz could you dig into this?

**Comment by tubiz** [comment]
@pippinsplugins I will need a copy of the Zippy Courses plugin

**Comment by pippinsplugins** [comment]
Copy sent!

**Comment by tubiz** [comment]
@michaelbeil I have been unable to replicate this issue. 

From the debug log above, the reason why the referral wasn't created was because the `affiliate_id` used to create the referral is `0` which is strange because the visit was recorded for the affiliate with `affiliate_id` `4`

From your test which gateway are you using and how is your environment setup. Is it a multi-site or single site.

**Comment by michaelbeil** [comment]
Alright, I'm getting in touch with the customer about the environment setup.

I have not been able to replicate this issue yet on a multisite using Stripe.

**Comment by michaelbeil** [comment]
Referrals are not being generated when on PayPal live mode.

Referrals are being generated on Stripe test/live mode and PayPal test mode.

Here is what the customer says: 

>- Create a course
>- Create a product that contains that course
>- Add paypal as payment method, set to pay first
>- Create an affiliate
>- Buy the product with a new user through the affiliate link
>- Referral fails as indicated by the error message generated in the integrations
>- [base class](https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/integrations/class-base.php) around line 157 because affiliate_wp()->referrals->add( $args ); is not returning
>- an affiliateID

>I don't know what is inside "args", but my suspicion is there is missing
information. You may need to contact Zippy Courses about where to get the
information needed for that function as it doesn't seem to be available
through the hook you are currently using.

@tubiz Do you have any ideas on my referrals are not being generated when on PayPal live mode?

**Comment by tubiz** [comment]
@michaelbeil I will test again on PayPal live mode. Can the customer use another affiliate link to test again?

**Comment by michaelbeil** [comment]
Alright. I will check with the customer to test with a different affiliate link.

**Comment by michaelbeil** [comment]
The customer tested with a different affiliate link and a referral was successfully generated. 

@tubiz Are you able to generate a referral on PayPal live mode?

**Comment by tubiz** [comment]
@michaelbeil I have't been able to test on PayPal live mode.

**Comment by michaelbeil** [comment]
@tubiz Alright. 

@pippinsplugins I am not quite sure how to test in PayPal live mode. It seems like a [PDT Token](http://s14890.p27.sites.pressdns.com/wp-admin/admin.php?page=zippy-settings&tab=zippy_settings_payment) is required, but I cannot enable this without a PayPal business account: https://developer.paypal.com/docs/classic/products/payment-data-transfer/. 

Can you add this to the test site?

**Comment by michaelbeil** [comment]
Customer just said:

>Everything seems to be working now! As strange as it seems, I think there was a some kind of problem with that specific user account. Now that I'm not using it, everything seems to work
and I think we can close this out. Sorry it's so inconclusive, but I don't think this was related to AffiliateWP based on everything else we've seen. Thinking back on it, that account was created before I made the switch to multisite, so it could be some obscure condition coming from those
particular circumstances.
