### ISSUE TITLE
This error is showing up on the payouts table

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#2743]
A customer is experiencing the following error:

>Fatal error: Uncaught Error: Call to a member function date_i18n() on boolean in /home/s793/html/wp-content/plugins/affiliate-wp/includes/admin/payouts/class-list-table.php:397 Stack trace: #0 /home/s793/html/wp-admin/includes/class-wp-list-table.php(1249): AffWP_Payouts_Table->column_date(false) #1 /home/s793/html/wp-admin/includes/class-wp-list-table.php(1192): WP_List_Table->single_row_columns(false) #2 /home/s793/html/wp-admin/includes/class-wp-list-table.php(1180): WP_List_Table->single_row(false) #3 /home/s793/html/wp-admin/includes/class-wp-list-table.php(1165): WP_List_Table->display_rows() #4 /home/s793/html/wp-admin/includes/class-wp-list-table.php(1097): WP_List_Table->display_rows_or_placeholder() #5 /home/s793/html/wp-content/plugins/affiliate-wp/includes/admin/payouts/payouts.php(57): WP_List_Table->display() #6 /home/s793/html/wp-includes/class-wp-hook.php(286): affwp_payouts_admin('') #7 /home/s793/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #8 /home/s793/html/wp-includes/plu in /home/s793/html/wp-content/plugins/affiliate-wp/includes/admin/payouts/class-list-table.php on line 397  

Related to https://github.com/AffiliateWP/AffiliateWP/issues/2729.

Ticket: https://secure.helpscout.net/conversation/600924552/84152?folderId=634609.

**Comment by DrewAPicture** [comment]
Is this the same customer as before?

**Comment by michaelbeil** [comment]
Yes, it is.

**Comment by tubiz** [comment]
I just checked the state of the `payouts` and `affiliates` tables on the website, there are `163` payouts with a `payout_id` of 0, likewise there are `2741` affiliates with `affiliate_id` of 0.

**Comment by DrewAPicture** [comment]
There's certainly a case to be made for ensuring that errors like this don't get surfaced, however this particular site seems to have a habit of corrupting data and/or containing invalid records. That said, at a certain point we have to consider that the software is intended to work in the ideal condition of not having outside forces messing with the integrity of the data.

Translation: Something on this site is messing with the data and the errors, while something we can attempt to mitigate, are likely caused by third-party code.

**Comment by DrewAPicture** [comment]
Because we're all about an awesome experience, we're willing to try to mitigate errors stemming from corrupted records. I mostly just hesitate to dive too deeply. We should try wherever possible to ensure that _even if outside forces are at work_, to handle for it. The main concern is the precedent set for needing to dive so deep and reach so far to ensure nothing can wrong is endless.

**Comment by tubiz** [comment]
PR: #2745

**Comment by michaelbeil** [comment]
@tubiz How can I test this?

**Comment by tubiz** [comment]
@michaelbeil you can test using this branch https://github.com/AffiliateWP/AffiliateWP/tree/issue/2743

To replicate the issue modify any payout and set the `payout_id` to `0`

**Comment by michaelbeil** [comment]
Ah okay, thanks! PR fixes the issue!
