### ISSUE TITLE
Pretty Affiliate URLs & Warfare Plugins

### ISSUE THREAD

**Issue by BurlesonBrad** [AffiliateWP/AffiliateWP#2768]
Ref: https://github.com/warfare-plugins/social-warfare/issues/257

I've learned to setup sites w/ the Pretty URLs long ago & to never use the ```/?var=ID``` option.

When AffiliateWP is coupled with Social Warfare, magic happens for everyone's wallet by appending each and every social share with a financial incentive to whack those whimsical buttons.

The problem though has come up that when using Warfare Plugin's newest plugin: https://github.com/warfare-plugins/social-warfare-affiliatewp with the aforementioned Pretty URLs, things don't want to work correctly.

It's only when using the ```/?var=ID``` option _(Pretty URLs toggled **off**)_ in which things work.

**Comment by pippinsplugins** [comment]
This isn't an AffiliateWP bug. If we look at the code in the Social Warfare plugin, we see this:
```php
 $buttons['url'] = add_query_arg( affiliate_wp()->tracking->get_referral_var(), affwp_get_affiliate_id(), $buttons['url'] );
```
That piece needs to be updated with support for pretty URLs by adding the necessary logic to detect and construct pretty URLs.

Since that is outside of AffiliateWP's control, I'm closing this as invalid.
