### ISSUE TITLE
Add a REST API via WP API

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#316]
* [x] PR: #1436
* [x] Authentication: #1551 

We should create a full JSON API by implementing an extension of the WP API.

This will allow us to make referral / affiliate / visits data available in JSON so we could built stat apps for iOS, Android, etc.

We could also support creating / updating referrals, affiliates, etc.

**Comment by michaelbeil** [comment]
Are we looking at this for v2.0, perhaps?

**Comment by pippinsplugins** [comment]
Yep!

**Comment by michaelbeil** [comment]
To clarify, that would be for AWP 2.0, correct?

Not to be confused with v2 of WP-REST-API.

**Comment by pippinsplugins** [comment]
Request: https://secure.helpscout.net/conversation/188085047/31277/?folderId=205524

**Comment by michaelbeil** [comment]
Related: #1100

**Comment by DrewAPicture** [comment]
It has begun. PR: #1436

**Comment by pippinsplugins** [comment]
Looking good!

I think we should use `WP_REST_Response` when returning the data.

**Comment by pippinsplugins** [comment]
We need to be sure that we introduce versioning from the beginning with this as well. The REST namespace is `affwp/v1` but I think it should go a little further than that.

I propose we add a `includes/REST/v1` folder that contains each of the routes. That way when it comes time to introduce `v2`, we simply add a second folder and do not need to worry about moving files (potentially breaking other plugins if someone has hardcoded a path) and makes it extra clear that there is versioning.

**Comment by ramiabraham** [comment]
What would the endpoints be presently? I've tried the `site/wp-json/affwp/` namespace and some variants so far.

**Comment by pippinsplugins** [comment]
`/wp-json/affwp/v1`

**Comment by pippinsplugins** [comment]
API key authentication is looking good!

A few quick items I noticed on the API keys page.

1. The username field needs to have a placeholder so admins know what to enter: https://cloudup.com/cUOxHxuN1vC
2. Let's move `API Keys` to the second position, in front of `Recount stats`
3. `Revoke` link could be red to indicate it's a "delete" link: https://cloudup.com/c3ULvePptgX
4. Once we have documentation written, let's add a link below the API keys table to it. Something like `Need help using the API? See our documentation.`

**Comment by pippinsplugins** [comment]
I've found a few minor bugs.

1. `get_collection_params()` mentions a `per_page` parameter. The individual routes, however, use `number`, not `per_page` to control how many are returned.

2. The `page` parameter does not appear to function. Page 1 is always loaded.

3. The `user=true` parameter for the affiliates route does not appear to work. No user data is returned with or without the parameter.

**Comment by DrewAPicture** [comment]
Added endpoints for Payouts.

**Comment by DrewAPicture** [comment]
**Testing REST Endpoints**

Needed Tools:
* Browser
* Postman app (Chrome or Mac): https://www.getpostman.com/
* AffiliateWP checked out on the `issue/316-api` branch

Background:
Our five core objects (`affiliates`, `creatives`, `payouts`, `referrals`, and `visits`) each have their own GET endpoints. One each for listing of the objects, and one each for retrieving a specific object.

The namespace for our REST API is `affwp/v1`, thus, requests are made against URLs with the following format: `http://site.dev/wp-json/affwp/v1/{endpoint}`

For affiliates, the two endpoints would be:
`http://site.dev/wp-json/affwp/v1/affiliates` (list affiliates)
`http://site.dev/wp-json/affwp/v1/affiliates/ID (single affiliate)

The same goes for the other four objects. For affiliates, you can also pass `?user=1` to the end of the single affiliate endpoint to additionally retrieve a field containing user data:
`http://site.dev/wp-json/affwp/v1/affiliate/ID?user=1`

*Set Up*

In order to proceed, you will need to have checked out the `issue/316-api` branch and visited your admin to trigger the upgrade routine for 1.9 which adds a `payout_id` column to the referrals table and creates the `payouts` and `rest_consumers` tables.

You'll also need to have installed and opened Postman.

If the all of the above are ready to go, you can follow this video to get Postman set up with authentication for the REST API: https://cloudup.com/cxI7dtj34q8

---

*Testing Arguments*

This testing guide assumes you have dummy objects to test against. If you need to create some, this is accomplished easily enough from the command line, see `wp affwp create affiliate|creative|payout|referral|visit`.

As briefly demonstrated in the first video, you can retrieve a list of accepted parameters by sending an `OPTIONS` request to the endpoint. As is demonstrated in the following video, probably the easiest way to test is to have an `OPTIONS` request open in one tab for reference and a `GET` request in another that you test entering parameters against.

Video for testing endpoint parameters: https://cloudup.com/ctm0aYuOtiC

**Comment by ramiabraham** [comment]
The cap check for `manage_shop_settings` is causing api key generation to fail in `class-rest.php L:82` at `6e51f834`, is anyone else getting that?

Commenting out the `wp_die` resolves the issue.

**Comment by DrewAPicture** [comment]
@ramiabraham Should be fixed in 465f943. That cap was leftover from the EDD code we reused.

**Comment by pippinsplugins** [comment]
#1551 has been merged into `issue/316` so the complete API is now in `issue/316`.

**Comment by sumobi** [comment]
@DrewAPicture @pippinsplugins 

I noticed there was no "unpaid referrals" count in either `/affiliates` or `/affiliates/8`. Is that something we can add?

Updates the above `http://site.dev/wp-json/affwp/v1/affiliate/ID?user=1` to `http://site.dev/wp-json/affwp/v1/affiliates/ID?user=1` - missing an `s`.

**Comment by sumobi** [comment]
Super awesome stuff, thanks for the setup vids.

Stupid question but I haven't been following along until now - `GET` works great in my testing but how can I `POST` and change stuff? Ie add referrals etc.

**Comment by ramiabraham** [comment]
@sumobi Yup, `POST` is not yet supported.

**Comment by DrewAPicture** [comment]
@sumobi We could add something like a `count` argument to the affiliates endpoints, but we wouldn't want to do it on the base endpoint responses because it's an extra query. Similarly, that's why grabbing the user data is a separate argument.

**Comment by pippinsplugins** [comment]
Let's log that as an enhancement for 2.0.

**Comment by DrewAPicture** [comment]
Tests passed, merged #1436.

**Comment by pippinsplugins** [comment]
💯

**Comment by michaelbeil** [comment]
🎉 🎈
