### ISSUE TITLE
CSV import for affiliates and referrals

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#338]
We should provide a way to import affiliates and referrals via a CSV file.

Related #337 
PR: #1891

**Comment by pippinsplugins** [comment]
This should be supported in core and is something we definitely want to support so re-opening.

**Comment by sumobi** [comment]
Another request for CSV importing. Customer is coming over from https://www.getambassador.com/.

Having a CSV importer for affiliates/referrals would be so helpful. Similar to EDD's, I'd imagine we just map the column data to specific values inside AffiliateWP.

**Comment by pippinsplugins** [comment]
Let's try and do it for 2.0.

**Comment by wordmaid** [comment]
Along the same lines, this customer wants to be able to import affiliates: https://secure.helpscout.net/conversation/256116186/43271/?folderId=205524

**Comment by DrewAPicture** [comment]
Definitely. It would be nice if we could (at the very least) make our exports importable.

**Comment by wordmaid** [comment]
Yes! 👍

**Comment by swise23** [comment]
We also need the import affiliates option.

**Comment by DrewAPicture** [comment]
I started a PR that we can launch off of when we're ready in 2.1: #1891

TODO:

* [ ] Build CSV field mapping UI a la EDD
* [ ] Implement referral imports via extending `Batch\Import` and related CSV interfaces
* [ ] Implement affiliate imports via extending `Batch]Import` and related CSV interfaces

**Comment by DrewAPicture** [comment]
@AffiliateWP/core  This is now ready for testing.

Note that this PR implements the _architecture_ for batch imports as well as the _affiliate importer_ rather than the _referral importer_. Once we've worked out some of the kinks, it should be fairly simple work to do referral imports.

To test, you're looking for the Import Affiliates box in Tools > Import/Export:
![Import Affiliates](https://cl.ly/2X0Y2O2D3x3F/Screen%20Shot%202017-04-01%20at%2012.00.48%20AM.png)

Notable feedback:
* Any JavaScript errors
* Any fields not properly mapped
* Any fields you feel like are missing (remember, we're using our own affiliate exports as a model)
* Any breakage with any already-existing batch processes

Expectations:
* If the user already exists and is an affiliate, it will be skipped
* New users will be created using the Username value first, followed by a sanitized version of the email, followed by a generic affiliate####
* Statuses for new affiliates will follow existing logic in `affwp_add_affiliate()`, which means that if approval is required, they'll be set to "pending" etc.
* Mapping the "Email" field is required because we need it to create the new user and/or derive a username for said user/affiliate

**Comment by pippinsplugins** [comment]
@DrewAPicture Looking good! I've done a quick import test and it all worked! Just three small issues:

1. We should exclude blank columns from the select field:
![screen shot 2017-04-03 at 9 12 12 pm](https://cloud.githubusercontent.com/assets/1034109/24638986/50441c6e-18b2-11e7-98ae-9263acc689b3.png)

2. This import was for just two affiliate accounts but the success message is wrong:
![screen shot 2017-04-03 at 9 10 40 pm](https://cloud.githubusercontent.com/assets/1034109/24638993/56a816d2-18b2-11e7-8f73-8f4a84b57553.png)

3. The spinner is wrongly positioned (should be far right):
![screen shot 2017-04-03 at 9 12 40 pm](https://cloud.githubusercontent.com/assets/1034109/24638995/5c2e3834-18b2-11e7-8ccc-c10e238aa13c.png)

Great work!

**Comment by sumobi** [comment]
Nice work,

1. Feedback that you didn't want because you already knew it. There's text in the metabox that says: `See this guide for assistance with importing payment records. `

2. It's possible to show the notice multiple times by hitting the button over and over.

    <img width="1095" alt="screen shot 2017-04-05 at 5 37 51 pm" src="https://cloud.githubusercontent.com/assets/52581/24691278/a5aca37c-1a26-11e7-9f2b-9a9273ff9aba.png">

3. The "Affiliate Field" column in the admin lists `First Name` and `Last Name` whereas the affiliates .csv file that AffiliateWP exports only has a `Name` column. When importing, you can only map the `name` field from the .csv file to the `First Name` in the importer. Since the `Name` column can have both first and last names, this would lead to the new WP user having a first name that is made up of both first and last name.

    Since we use `Your Name` on the affiliate registration form and in the export affiliates .csv file should we change it so we only have `Name` as the field in the importer? On the other hand, the importer can generate WordPress user accounts so having First and Last Name would be awesome. Maybe we should fix our export .csv option to export first and last name instead?

4. This little button can be removed 

    <img width="153" alt="screen shot 2017-04-05 at 5 41 42 pm" src="https://cloud.githubusercontent.com/assets/52581/24691371/280112f4-1a27-11e7-9c40-5c4ad5cc7875.png">

5. Can we auto detect and map the fields if there's a match? Would save some time mapping.

**Comment by DrewAPicture** [comment]
@pippinsplugins 

* 1. Empty columns are removed as of d360ec88ac5d9ca8ee234b4268c4cb0ce7323fdb
* 2. I'll look into it and get back to you
* 3. The spinner should now show adjacent the the Process Import button as of 2b8ba07b796db3fb409d546c50bb4984a3c12c2f

@sumobi 

* 1. Fixed as of 96fdaddaf162834caae6edee955281b38f59e939
* 2. The notice will now be hidden each time Process Import is clicked as of 46eded2ad349800ecb79ee5896c4bc86c5fc0d3e
* 3. This is kind of a nuanced problem because there isn't a real affiliate "name" – it's built using the first and last name of the associated user account. In the import script, it currently handles adding the new user's first and last name via user meta fields. To support the "Name" column in our Affiliates exports, I'd suggest changing the "First name" label to "First/full name" and then simply check for both a space in the value and a blank "Last name" value or something. 
* 4. Removed as of a3cea2c94926016aeb704f9992706131eadcd581
* 5. Auto-detection is hard and not necessarily something I'd recommend as a v1 feature

**Comment by pippinsplugins** [comment]
@DrewAPicture looking good!

**Comment by gspice** [comment]
So glad to have this feature!

First test, importing.   Not knowing the exact format needed of the import file, I created one using pipe-delimited format.  

1. select the file, clicked import
2. page refreshes but nothing happens

Assuming it's looking for a true comma-delimited format, would expect an error message of some kind to say the file was not formatted correctly ....perhaps direct them to a document section?


[affiliates-100-a.csv.zip](https://github.com/AffiliateWP/AffiliateWP/files/922816/affiliates-100-a.csv.zip)

**Comment by DrewAPicture** [comment]
Note for testers, you can use this tool to generate CSV files: https://www.mockaroo.com/

@gspice It looks like the affiliates-100-a.csv file is invalid. The first column has pipe-delimited data and then there's an extra column, which is what's throwing off the importer. Looking into the issues with your comma-delimited files.

**Comment by DrewAPicture** [comment]
The running counts issue should be resolved as of bab2d169d7198787f0ddea52591b0e85a6b29465.

**Comment by gspice** [comment]
Note for testers, must have ```define('SCRIPT_DEBUG', true );``` in your wp-config file or nothing will happen as I found out :-)

**Comment by gspice** [comment]
Tested mapping the required **Email** field to a column that contained a first name, i.e. not a valid email address.   When I clicked the **Process Import** button , it gave me a correct message at the bottom :

```No new affiliates were imported.  20 other existing affiliates or invalid rows were skipped.```

However, it imported all 20 records, created a username from the last-name that was mapped to email, but left the email address blank in the WP user account.

![invalid-email](https://cloud.githubusercontent.com/assets/3018245/25921580/d3be2b6c-358a-11e7-92e0-fe26b39065d1.png)

![users-created](https://cloud.githubusercontent.com/assets/3018245/25921614/fc68f132-358a-11e7-9517-fa3caae0d874.png)

**Comment by gspice** [comment]
Fields suggested to add to the import:

- payment/paypal email (optional)
- website (optional)

**Comment by pippinsplugins** [comment]
I agree with Ginger, we need to support those fields as well.

I just tested an import and got this message:

>>>161 affiliates were successfully imported. 839 other existing affiliates or invalid rows were skipped.

My CSV has 1,000 rows. Every row has a name and email and then some rows have values for all other, optional fields.

I'm not sure why so many rows would have been skipped. Pretty sure that's a bug but I'm not sure which field is causing it to fail.

CSV I used: https://www.dropbox.com/s/zo09myh82sy9umr/MOCK_DATA%20%282%29.csv?dl=1

My field mapping: 
<img width="1445" alt="screen shot 2017-05-11 at 10 54 34 am" src="https://cloud.githubusercontent.com/assets/1034109/25959093/42c8b70e-3638-11e7-828c-e9156771ae50.png">

**Comment by swise23** [comment]
Most likely duplicate usernames?

Susan Wise
Marketing Automation Specialist
BizBudding Inc.
susan@bizbudding.com
(877) 548-2440 x 701

**Comment by pippinsplugins** [comment]
Ah yes, that could be it!

**Comment by pippinsplugins** [comment]
Yep that was it!

**Comment by pippinsplugins** [comment]
@DrewAPicture A few notes:

1. The following fields need to be supported: status, payment_email, website
2. Visit count does not get imported even when set. Always shows 0.
3. Referral count does not get imported even when set. Always shows 0.
4. Unpaid earnings does not get imported even when set.
5. Paid earnings does not get imported even when set.

**Comment by pippinsplugins** [comment]
We also need to ensure the import system can be extended by add-ons (think adding support for importing custom affiliate slugs). At minimum, looks like `affwp_get_affiliate_import_fields()` and `affwp_get_referral_import_fields()` need filters added to them.

**Comment by DrewAPicture** [comment]
@pippinsplugins 

* Filters have been added to the import field getters as of bc5b5e0a55c7cc294af89cf82899d3897496796e
* Visits and referrals should now be set on add as of 7655037932840d78172b6758131cf636ad94ee7e
* Support has been added for `status`, `payment_email`, and `website` as of fec58463dcc301229344a71a4ad85509707ad312

I haven't looked yet, but I'm assuming paid/unpaid earnings suffer from the same lack of support that setting visit and referral counts did. Will follow up.

**Comment by DrewAPicture** [comment]
Yuppp. Earnings and unpaid earnings are now set as well as of 4b49839778e21d98936e82f48e18f88367b93968.

**Comment by pippinsplugins** [comment]
New fields work great! As do the count and earnings fields that were not previously working.

**Comment by pippinsplugins** [comment]
I don't think the referral import should have any of the affiliate account fields:
<img width="653" alt="screen shot 2017-05-15 at 11 32 27 am" src="https://cloud.githubusercontent.com/assets/1034109/26068168/38d2b68c-3962-11e7-9e58-73cd2c761307.png">

**Comment by pippinsplugins** [comment]
Other than that, the referral import worked beautifully.

**Comment by DrewAPicture** [comment]
You have to have the affiliate field at the least because it's required to associate the referral (and/or create the new affiliate account) but also because those fields are present in our exports ;)

**Comment by pippinsplugins** [comment]
Does importing referrals also support creating a new affiliate?

**Comment by DrewAPicture** [comment]
Yep :-)

**Comment by DrewAPicture** [comment]
See `maybe_create_affiliate()`: https://github.com/AffiliateWP/AffiliateWP/pull/1891/files#diff-6b03fe4991f47dca50eafabddd32c27eR146

**Comment by pippinsplugins** [comment]
Sweet! let's get that added as help text on the import screen to make it more well known.

**Comment by gspice** [comment]
CSV importing affiliates works a treat!   Only thing that was off , it didn't like my date column.  What format is it expecting?  I used `1/20/2017'

**Comment by gspice** [comment]
Importing email (required) field, it still allows me to import using a value that is not an email address.

**Comment by DrewAPicture** [comment]
@gspice 

> Only thing that was off , it didn't like my date column. What format is it expecting? I used `1/20/2017`, `5/11/2017`

Turns out that we don't actually support setting the date when adding new affiliates. I've opened a separate issue for that: #2218

> Importing email (required) field, it still allows me to import using a value that is not an email address.

We decided in Slack a few minutes ago that we'd hold off on validating actual row values on import, so we're just going to have to trust that users map reasonably ;)

**Comment by DrewAPicture** [comment]
@gspice #2218 has been merged, adding support for setting `date_registered` when adding affiliates. So if you could retest importing affiliates with specified dates it would be appreciated :-)

**Comment by gspice** [comment]
@DrewAPicture Re-tested using same file and latest from branch:

- Date imported, but was -1 for each day:  file had 5/11/17, imported as 
- website URL did not import

**Comment by DrewAPicture** [comment]
@gspice #2225 has been merged, which means that affiliates should now be imported with the date from the file instead of taking the site timezone settings into account. Can you please retest that point?

Looking into the website part.

**Comment by DrewAPicture** [comment]
I've filed #2227 (PR: #2228) to handle setting the website when adding an affiliate.

**Comment by DrewAPicture** [comment]
@gspice Now that #2227 has _also_ been merged, import affiliate websites should also work. If you could retest that in addition to the dates issue, it would be appreciated :-)

**Comment by gspice** [comment]
@DrewAPicture 

Verified:  
* Date inserted matches date in file
* Website url now populated
* Status - hadn't previously tested but all variations import correctly:  inactive, active, pending.

All looks good!

**Comment by DrewAPicture** [comment]
I think we're about done here. I have three things that I've identified as "left to do":

* [ ] Update each row's preview during auto-mapping
* [ ] Support for auto-mapping our own exports (handle capitalized headers, basically)
* [ ] Add help text RE: referral imports creating affiliates that don't already exist

**Comment by DrewAPicture** [comment]
Each row's preview is now updated during auto-mapping as of b5f8dbbd1254ffb11934fee0c83ec412a31965fc.

**Comment by DrewAPicture** [comment]
Fields from our own exports now auto-map as of 94946864018b5dacb3ddc22ac84e7de7e2b67b2a.

**Comment by DrewAPicture** [comment]
Help text added as of 19f35039fac603c2e2b46f7617064a28c7b9c8fb.

**Comment by DrewAPicture** [comment]
@AffiliateWP/core This is ready for final review! 🎉

**Comment by pippinsplugins** [comment]
I'm 100% happy with this, merging!
