### ISSUE TITLE
Display notice after import when using migration assistants

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#397]
PR: #1786

When using either the Affiliates Pro or WP Affiliate migration assistant we should show a notice when it has finished. At the moment it redirects to the overview page and it's not clear whether it worked or not.

Something like:

`Nice! 34 affiliates were successfully imported into AffiliateWP`

**Comment by michaelbeil** [comment]
This would be great.

**Comment by DrewAPicture** [comment]
Added a PR for the user migration script: #1786

Since I added methods to the base migration class, adding counts to the other notices should be fairly quick work.

To test (currently use the user migration script):
1. Create some non-affiliate users, e.g. `wp user generate --count=55`
2. Navigate to Affiliates > Tools > Migration Assistant
3. Scroll to the "User Migration" section
4. Click the "Create Affiliate Counts for Users" button
5. Once the script has completed, you should see the resulting admin notice and it should include a properly formatted string based on the number (singular for 1 affiliate, plural for multiple)

**Comment by pippinsplugins** [comment]
Just tested but not seeing anything. Import worked fine but no notice was shown.

**Comment by michaelbeil** [comment]
Notice shows well for me: 
![screen shot 2016-11-03 at 9 35 33 pm](https://cloud.githubusercontent.com/assets/4752949/19984193/7e8b80f6-a20d-11e6-8d6c-d14760b88822.png)

**Comment by pippinsplugins** [comment]
@sumobi?

**Comment by sumobi** [comment]
Yep works fine for me

<img width="302" alt="screen shot 2016-11-04 at 8 53 05 pm" src="https://cloud.githubusercontent.com/assets/52581/20027395/be3b2490-a2d0-11e6-9422-b64e2fb9856a.png">

**Comment by DrewAPicture** [comment]
I've added migration completion notices for both the WP Affiliate and Affiliates Pro migration scripts as well. Needs testing.

**Comment by michaelbeil** [comment]
No idea how to test the WP Affiliate and Affiliates Pro migration scripts . Do we have copies?

**Comment by pippinsplugins** [comment]
We do. They're in the Dropbox folder.

**Comment by michaelbeil** [comment]
WP Affiliate Platform migration completion notice works.

**Comment by michaelbeil** [comment]
Affiliates Pro migration completion notice works as well. 
![screen shot 2016-11-11 at 3 35 20 pm](https://cloud.githubusercontent.com/assets/4752949/20218352/80346446-a824-11e6-9cad-02ef29062c8e.png)

**Comment by michaelbeil** [comment]
Should this notice be displayed on the affiliates screen instead of the overview screen?

**Comment by pippinsplugins** [comment]
Yes, I think we should redirect to `Affiliates` instead of `Overview`.

**Comment by DrewAPicture** [comment]
Updated the PR to redirect both to the Affiliates screen instead of Overview.

**Comment by michaelbeil** [comment]
Great!
