### ISSUE TITLE
Collecting tax ID info on the settings tab of the affiliate area  

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#517]
A customer has suggested including a field to collect tax ID info on the settings tab of the affiliate area. Going to add it here for discussion.

<blockquote>
Have you considered adding a field to collect tax ID info on the settings tab of the affiliate area, or ask for it during signup? In fact, this might make for a premium add-on. I'd buy it!

I'd imagine you'd want to make sure SSL is required and the server its being run on is PCI compliant, since you're storing a lot of social security numbers.

I did some preliminary research, and you'd want to make sure the table in the database is using at least AES128. It might also be a good idea to require a third party plugin like https://wordpress.org/plugins/wpclef/ to reduce security breaches.

Well, now that I've gotten this far, storing SSN's on a WordPress database seems like a terrible idea. It'd be great if there was a secure way to integrate your affiliate plugin with something more secure than WordPress. I imagine a lot of buyers are using shared hosting and don't have the luxury of modding their servers.
</blockquote>

**Comment by pippinsplugins** [comment]
I'm really reluctant to start storing tax IDs numbers, especially social security numbers in the DB.

I'm all for integrating with a service but I really don't think we should allow site owners to store them. Too much risk.

**Comment by sumobi** [comment]
:+1: absolutely. I'm unaware of any services to integrate with. We can list them here if any come to light.

**Comment by TimothyBJacobs** [comment]
FWIW EIN numbers aren't sensitive.

**Comment by pippinsplugins** [comment]
Right, but SSNs are, and a lot of people would enter them without considering it.

**Comment by servesense** [comment]
I just wanted to comment on this.  I'm looking for a solution for this as well.  In the U.S., you're required to submit 1099 forms for any affiliate earning over a certain amount (either $400 or $600, I have to get clarification).  If you don't do this, you may have to pay taxes for the affiliate, essentially, and there are heavy penalties.  It's not worth taking risks with.  Really, you need a signed W9 form (it can be electronically signed) on file for each affiliate.

As others here mentioned, I don't like the idea of storing all this on my site.  But I need it somewhere.  And it seems like it would make sense to at least be submitted through my site.

I was thinking even if the tax info wasn't done through the plugin, if there was an option I could select for each affiliate when I've received their form to make them eligible for payouts, that would help.  I know I could manually approve affiliates but I don't want to prevent them from promoting, I just want to hold onto their commissions until they've submitted the necessary tax info.  So it would be nice if there was just an option to make affiliates eligible for payouts or not and any that aren't eligible won't be included in payouts but their balance will still be there for when they do get it submitted.

I know of a service that is supposed to manage this stuff for you, and it sounds pretty good.  It's called PayPeopleOnline.com.  Your affiliates have to register with them and submit their tax info and then when you do payouts, you submit your Mass Pay file to them and they "scrub" it, removing any affiliates that haven't submitted tax info but keep a record of what you owe them for when they get it submitted.  Then it outputs a new MassPay file that has only approved affiliates.  It sounds great.  But there are 2 things I don't like.  

1) Their security certificate apparently expired last month and they haven't renewed it.  So I'm getting security warnings on the site.  I know they're legit because they've been around quite a while but I can't send affiliates to submit their sensitive info on a site with security warnings.  I've contacted them about this and hope they'll get it fixed.

2) It charges the affiliate a small fee every time you pay them.  It subtracts the fee from the affiliate's commissions.  In reality it's not a lot, but it's every time.  The affiliate really isn't getting any benefit from that, I am.  It would be saving me on administrative hassle and time.  So it seems more logical to me that the business owner would pay the fee rather than the affiliates.  It's not a huge deal but I think I'd at least like the option to pay the fee rather than the affiliate since I'm the one benefiting from it.

Anyway, if they get their security warnings taken care of I may go that route.  Maybe other people would find it beneficial too.  By the way, I've never tried it, but if it does what it says it does, I think it would be nice.  Maybe there could even be some way for AffiliateWP to partner with them and integrate with them?

**Comment by flowdee** [comment]
:+1:

**Comment by pippinsplugins** [comment]
This is handled really well through https://wp1099.com/ so I'm going to close this as wontfix now.
