### ISSUE TITLE
Issue with affwp_register_user hook

### ISSUE THREAD

**Issue by tubiz** [affiliatewp/AffiliateWP#667]
Am working with a AffiliateWP customer to fix an issue with a function hooked to the affwp_register_user action not working.

After troubleshooting the issue I noticed that a wrong value for affiliate_id was being passed.
This seems strange.

Below are the values of the wrong affiliate_id that was being passed on the left and the correct affiliate_id on the right.
1571  - 34 
1595  - 35
1691  - 36

Am so confused right now as to what the problem is, the right affiliate_id is being passed in my test env but on the client site the wrong value is being passed.

**Comment by sumobi** [comment]
I have actually seen this once before, also on a live site and couldn't replicate locally. If you get the customer to disable all other plugins does it pass the affiliate ID correctly? I wonder if another plugin is something interfering.

**Comment by pippinsplugins** [comment]
I wonder if this is a case of accidentally passing the user ID instead of the affiliate ID.

**Comment by sumobi** [comment]
@tubiz did you ever figure out why it happens? Is what I've described below what you've seen?

Just came across this again on a customer's site. No other plugins active beside AffiliateWP 1.6.5, theme at 2015, hosted on GoDaddy. 

The affiliate ID is being passed to the emails directly after registration is `116635`. The affiliate is still created and given the correct ID of `61` for example. Their user ID is `48. 

Because of the wrong affiliate ID being passed, it's not correctly passing the email tags in the admin registration email, and the affiliate is not receiving the first email at all. 

However, once you accept the affiliate it will send the email just fine as it now has the correct affiliate ID.

Any ideas @pippinsplugins?

**Comment by sumobi** [comment]
Just var dumped the `$user_id` and `$affiliate_id` in the `register_user()` function, right after they are created. Same thing:

$user_id = int(50) 
$affiliate_id = int(116635)

**Comment by tubiz** [comment]
@sumobi I never figured out what the problem was. 
What i later did to fix the problem was set a priority of 99 to the ```affwp_register_user``` hook.

**Comment by sumobi** [comment]
@tubiz hmm didn't seem to help in my case. Will get access to the customer's server again in a couple of days for some more digging.

**Comment by sumobi** [comment]
I have 2 open customer support tickets on this issue now, both using GoDaddy hosting:

https://secure.helpscout.net/conversation/109165215/13919/
https://secure.helpscout.net/conversation/107702367/13579/

**Comment by pippinsplugins** [comment]
I suspect that if we add the user's ID to the `$args` parameter of `affwp_register_user` and then use that user ID instead of pulling it from the database when sending emails, the problem will go away.

**Comment by sumobi** [comment]
@pippinsplugins I tested on 2 different customer sites hosted with GoDaddy and was able to get the correct `$affiliate_id` each time by adding:

`$affiliate_id = affwp_get_affiliate_id( $user_id );` 

right before:

`do_action( 'affwp_register_user', $affiliate_id, $status, $args );`

It seems that GoDaddy's caching can't get the correct $affilate_id here:
https://github.com/affiliatewp/AffiliateWP/blob/master/includes/class-register.php#L204

**Comment by sumobi** [comment]
@pippinsplugins we should try and get this in 1.7, see above. I've modified 2 customer's files so they work fine for now but it will break again if 1.7 doesn't have the fix.

**Comment by pippinsplugins** [comment]
:+1:
