### ISSUE TITLE
Add Iranian Toman currency

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#718]
PR: #1486

A customer has requested we add the Iranian Toman currency:
https://secure.helpscout.net/conversation/95079658/10109/

http://en.wikipedia.org/wiki/Iranian_toman

**Comment by fxbenard** [comment]
Talking about languages, the best way to add or not a language is to follow what's covered by WP Core:
http://wpcentral.io/internationalization/

**Comment by sumobi** [comment]
@fxbenard Sorry, my title isn't clear enough, this issue will be for adding a currency, not a language

**Comment by DrewAPicture** [comment]
@sumobi Just reading up a bit on the Toman and Rial. It seems that the Toman is a [superunit](https://en.wikipedia.org/wiki/Denomination_(currency)#Subunit_and_super_unit) of the Iranian Rial. We apparently have zero decimal support for the RIAL but it's not listed in the currencies. So I'm wondering if maybe we should just add support for the Rial since it's the official currency of Iran.

**Comment by DrewAPicture** [comment]
In the mean time, I've added a PR for adding the Iranian Toman. The rial has an official Unicode entity: `&#65020;`, no such luck for the Toman.

**Comment by sumobi** [comment]
👍

**Comment by fxbenard** [comment]
I don’t understand @DrewAPicture, why supporting an unofficial currency

**Comment by michaelbeil** [comment]
I think it'd be best for us to support the Rial instead of the Toman. Submitted a new PR: #1535.

**Comment by chimbaweb** [comment]
Yes, the official currency is Rial, but honestly everyone ( even the big cooperations ) show prices in Toman. Both ways are fine though.

**Comment by michaelbeil** [comment]
Thanks for further insight @chimbaweb!

**Comment by michaelbeil** [comment]
This can be closed as we resolved it further with #1534 by switching out the Iranian Toman for the Rial.
