### ISSUE TITLE
Simulation Feature

### ISSUE THREAD

**Issue by codelion7** [AffiliateWP/AffiliateWP#731]
I had a customer ask me about a Simulation feature, in which you could automatically test referrals, and in AffiliateWP MLM's case, Sub Affiliate signups as well. This could be accomplished with a form (possibly in the settings) that would allow the user to enter:

Simulation Type (Referrals, Registrations, etc)
Simulation Count (The number of times to loop through)
Simulation Affiliate (The affiliate id used for referrals)

@sumobi I think this could go nicely with the Test Mode  feature you mentioned here #674. What do you guys think?

**Comment by pippinsplugins** [comment]
In theory it sounds like a good idea but I'm not so sure that will prove to be the case in practice.

Most of the time when referrals aren't working properly it's due to a Javascript error (causing our JS tracking to fail). This simulation feature wouldn't account for those failures so site admins would be given the impression everything is working, when in reality, it's failing.

For MLM, however, having an option to generate a test referral makes sense as it would allow the admin to see the distribution of commissions and their amounts.

**Comment by DrewAPicture** [comment]
@pippinsplugins How would you like to proceed here?

**Comment by pippinsplugins** [comment]
This really hasn't been needed by any of our customers that I'm aware of, let's close as wontfix.
