### ISSUE TITLE
Paid Memberships Pro - Add referring affiliate and amount to order screen

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#756]
On a Paid Memberships Pro order, it doesn't list who the referring affiliate is, or how much they were awarded in commission. The only way to find this information from what I can see is to look on the referrals screen of AffiliateWP and find the order number.

**Comment by codelion7** [comment]
This can be easily accomplished by updating the affiliate for the order. We can add the code below after `$this->complete_referral( $order->code);` in class-pmp.php. 

`        $order->affiliate_id = $this->affiliate_id;
        $order->saveOrder();	`

We would need to change the action hook used from pmpro_add_order to pmpro_add_order and all references to `$order->code` to `$order->id`, as per my PR (#720), because this is the only way to get the correct reference (order id) for the order/referral.

**Comment by pippinsplugins** [comment]
How about adding it as an order note, similar to how we do with EDD? https://cloudup.com/cngxi08QlfH

**Comment by pippinsplugins** [comment]
@codelion7 I tried the method you proposed and it resulted in a lot of errors getting thrown.

**Comment by pippinsplugins** [comment]
Working now!
![screen shot 2015-09-02 at 10 21 54 am](https://cloud.githubusercontent.com/assets/1034109/9635521/7843c6ac-515c-11e5-9cc2-204d159d5f30.png)

**Comment by pippinsplugins** [comment]
Closing for now. @sumobi Re-open if you find anything in your testing.

**Comment by sumobi** [comment]
Looks like this never made it into 1.7, re-opening

**Comment by michaelbeil** [comment]
https://github.com/AffiliateWP/AffiliateWP/commit/fa1258e211cded49a3326214d809faa90643f0ca did not do it?

**Comment by pippinsplugins** [comment]
POS>

**Comment by pippinsplugins** [comment]
@sumobi it was merged into `release/1.7` . . . .

**Comment by sumobi** [comment]
@pippinsplugins It says that, but it wasn't some how :) the code isn't there, and the functionality does not work

**Comment by pippinsplugins** [comment]
Blarg
