### ISSUE TITLE
Account for spaces in affiliate usernames in affiliate URLS

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#843]
If an affiliate has a WordPress username with a space in it, eg `Dat Guy` then their affiliate referral URL won't work: 

`http://mysite.com/ref/Dat Guy`

or

`http://mysite.com/ref/Dat%20Guy`

WordPress itself doesn't let you register a username with a space in it however our affiliate registration form does. We should prevent spaces in usernames.

ref: https://secure.helpscout.net/conversation/121113989/17016/

![screen shot 2015-09-17 at 7 50 14 pm](https://cloud.githubusercontent.com/assets/52581/9927769/5c90e37a-5d75-11e5-97b6-388f89717835.png)

**Comment by TimothyBJacobs** [comment]
WordPress definitely allows Usernames with spaces. But when it generates the nicename it strips spaces and replaces them with dashes.

**Comment by pippinsplugins** [comment]
WP multisite doesn't permit them.

**Comment by TimothyBJacobs** [comment]
But why enforce the restriction on non-multisite installs? We have a fair amount of users with spaces in their username, it hasn't become an issue for affiliates yet, but the users would prefer to be able to use their same username if they do decide to become affiliates.

**Comment by pippinsplugins** [comment]
Personally, I'd say because spaces in usernames are just a terrible idea. Permitted or not permitted by WP. They just cause all sorts of unexpected problems. I'd vote that we mitigate potential issues and just not allow them through our registration forms.

**Comment by michaelbeil** [comment]
I am in agreement with @pippinsplugins. It'd be best to lessen the load of issues where we can.

**Comment by pippinsplugins** [comment]
@sumobi could you run this through some tests now? Merged into `master`

**Comment by sumobi** [comment]
:+1:

**Comment by sumobi** [comment]
@pippinsplugins works great for me

**Comment by ramiabraham** [comment]
@AffiliateWP/core  Re-opening; this continues to be an issue for some customers in cases where the affiliate does _not_ register via the AffiliateWP registration form.

In the affiliate area dashboard url generator, a space character present in the username results in an error indicating the url was not formatted correctly. 

Example: https://secure.helpscout.net/conversation/282832408/0/

What would we like to do here? 

Generally of course, space characters are a _terrible_ idea, but instead of _allowing_ it in AffiliateWP affiliate registration, we could account for this in search scopes by checking for a space character first, and if a user match is found, return _that_. 

That way, we can get the user, but not actively contribute to having gross usernames by permitting spaces in usernames in affiliate registration.

**Comment by pippinsplugins** [comment]
Spaces should work in URLs, even if we do not explicitly permit them.

**Comment by ramiabraham** [comment]
In testing against master at https://github.com/AffiliateWP/AffiliateWP/commit/c8659f60d52e6c53a73020c9dbde28e2086e87e7:

- URLS with a space character are not valid in the URL generator in the affiliate area dashboard

![ALT_TEXT](https://cldup.com/gBpVKLynYH.png "TITLE")


- URLS with a space character _code_ work fine, though:

![ALT_TEXT](https://cldup.com/77BDIeaXP0.png "TITLE")

**Comment by pippinsplugins** [comment]
We should allow them in the generator and automatically encode them.

**Comment by ramiabraham** [comment]
A small additional `replace()` does the trick in `frontend.js`. ([PR](https://github.com/AffiliateWP/AffiliateWP/pull/1864))

**Comment by DrewAPicture** [comment]
Fixed the spacing for the PR: #1864
