### ISSUE TITLE
Lifetime commissions not working due to change in v1.7

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#896]
@pippinsplugins Referrals generated by Lifetime Commissions are all being created at `0.00`.

The amount passed into the `insert_pending_referral()` function is also `0`, and I can trace it back to the `affwp_get_affiliate_rate()` function which changed quite drastically with in v1.7 (1.6.5 works fine).

Here's the exact line causing the issue:
https://github.com/affiliatewp/AffiliateWP/blob/master/includes/affiliate-functions.php#L207

In my test set up I have a global commission rate of `50%`. No per-product rate, and no per-affiliate rate.

If you var_dump $rate in the line above it's `0`. 

From what I can see it's 0 because the following line is trying to retrieve the per-affiliate rate, which this affiliate does not have (returns false).

`$affiliate_rate = affiliate_wp()->affiliates->get_column( 'rate', $affiliate_id );`

Then, it's rounding the false rate which becomes `0`.

`$rate = affwp_abs_number_round( $affiliate_rate );`

And finally, if null doesn't exactly match the rate, use this rate of `0`, else fallback to the product rate.

`$rate = ( null !== $rate ) ? $rate : $product_rate;`

Since it's using a 0 rate, this is being passed to the insert pending referral function, and hence why the referrals in lifetime commissions are also 0. There isn't a per-affiliate rate set so it should actually fallback to `$product rate`, which according to this line below, would actually then fallback to the default rate of 50%:

`$product_rate = ( null !== $product_rate ) ? $product_rate : $default_rate;`

I propose we change:
`$rate = ( null !== $rate ) ? $rate : $product_rate;`

into something like:

`$rate = $rate ? $rate : $product_rate;`

Can you see any issues with that?

I've tested referrals with the global rate, per-affiliate rate and per-product rate and all seems well so far.

**Comment by pippinsplugins** [comment]
This returns `null` for me, as expected.
```
$affiliate_rate = affiliate_wp()->affiliates->get_column( 'rate', $affiliate_id );
$rate = affwp_abs_number_round( $affiliate_rate );
```

**Comment by pippinsplugins** [comment]
I think it's because Lifetime Commissions is passing `0` as the `$product_rate`. When `0` is passed, it uses `0` instead of falling back to default.

**Comment by pippinsplugins** [comment]
I think I've tracked it down.

With Lifetime Commissions, `$this->affiliate_id` does not get set until the pending referral is created, which happens on the `affwp_insert_pending_referral` filter.

Before `affwp_insert_pending_referral`, the `calculate_referral_amount()` method of the base integration class is run. This method is expecting an affiliate ID to be present, but the affiliate ID is empty at this time.

`calculate_referral_amount()` calls `affwp_calc_referral_amount()`, which then calls `affwp_get_affiliate_rate()`.

`affwp_get_affiliate_rate()` should properly fallback to the site default rate when no rate for the affiliate is found, but it does not expect the `$affiliate_id` to be passed as an empty value. This causes a problem because of this line:
```
$affiliate_rate = affiliate_wp()->affiliates->get_column( 'rate', $affiliate_id );
```
When an empty value is passed to that line, `$affiliate_rate` coms back as `false`. Passing `false` to `affwp_abs_number_round()` returns `0` instead of the desired `null`.

There are two ways to fix this:

1. Make `affwp_abs_number_round()` return `null` when `false` is supplied
2. Force Lifetime Commissions to set the affiliate ID earlier so that it properly passes the ID to the rate calculation functions.

I propose we do both.

**Comment by sumobi** [comment]
@pippinsplugins Lifetime commissions is working well so far.

I attempted 2 yesterday using a new filter we added to set the affiliate ID however LC needs the payment ID to look up emails and such. I'll have another stab at it sometime, would love to filter the affiliate ID a lot earlier.

**Comment by pippinsplugins** [comment]
We can leave it like this for now.
