### ISSUE TITLE
Referrals not marked as complete with PayPal in iThemes Exchange

### ISSUE THREAD

**Issue by pippinsplugins** [affiliatewp/AffiliateWP#898]
Using PayPal, referrals are created but they are never marked as complete.

**Comment by sumobi** [comment]
Re-opening, it appears referrals are not being created at all in certain scenarios

**Comment by pippinsplugins** [comment]
I have an idea why.

**Comment by TimothyBJacobs** [comment]
The problem is that for PayPal Exchange uses transient transactions, so the session data might not be available when the transient transaction is converted to an actual transaction. The `it_exchange_generate_transaction_object` filter should be used to mark if the transaction was from an affiliate or not. Then that data can be used in the `it_exchange_add_transaction_success` hook. I can submit a PR if you'd like.

**Comment by michaelbeil** [comment]
That would be great @TimothyBJacobs!

**Comment by TimothyBJacobs** [comment]
Working on it now.

**Comment by michaelbeil** [comment]
:+1:

**Comment by pippinsplugins** [comment]
Thanks @TimothyBJacobs !

**Comment by TimothyBJacobs** [comment]
No problem!
