### ISSUE TITLE
Zippy Courses not generating referrals with PayPal sandbox/live

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#958]
Testing on a customer's site, referrals are not created with either PayPal sandbox or live. Stripe in test mode work's fine.

Can anyone else replicate?

@jwondrusch any ideas on this? can you confirm it works fine on your end with PayPal sandbox and live mode? Would you be able to send us the latest version of Zippy Courses? (andrew@affiliatewp.com)

**Comment by jwondrusch** [comment]
@sumobi We're working on replicating it on our end, I or Erik Jonasson will chime in this week  on it :)

**Comment by sumobi** [comment]
@jwondrusch thanks!

**Comment by ejonasson** [comment]
Hey guys, I've been working on this a bit and I think I see what's up. 

It looks like the pending referral from paypal is never created because the order in Zippy Courses is created via a Paypal Instant Payment Notification, and this notification doesn't have the correct cookie information to validate that the order is a referral. I believe that's something we can fix and submit to you as a pull request this weekend. We'll share that fix one we're able to resolve the issue.

Thanks!

**Comment by pippinsplugins** [comment]
Awesome, thanks!

**Comment by sumobi** [comment]
@ejonasson thanks!

**Comment by sumobi** [comment]
@ejonasson Works great, thanks again
