### ISSUE TITLE
2x Application Rejected emails visible when Require Approval setting is enabled

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#986]
When the Require Approval setting is enabled under the Misc tab, a second Application Rejected email appears in the Emails screen. This could perhaps be a wee bit confusing for admins. There is a slight name change between the two - the one that is always visible is "Application Rejected" and the one that appears when approval is required is "Application Rejection".

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/146724707/22920/?folderId=634609

**Comment by sumobi** [comment]
@pippinsplugins Pretty sure the "top" rejected email was added after the original. We should remove the following since a rejection email should only show if approval is enabled. It's also not being used anywhere: https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/admin/settings/class-settings.php#L499-L510 

We might have customers using the first instance of the email (although it won't send this one) and in which case we should consider writing a little upgrade routine if the second one is blank perhaps? IE if nothing in `rejection_email` copy across the content from `rejected_email`.

**Comment by pippinsplugins** [comment]
@sumobi please double check that ^

**Comment by sumobi** [comment]
@pippinsplugins I take it we're not going to worry about some kind of upgrade routine?

**Comment by sumobi** [comment]
@pippinsplugins Works great over here, emails still work etc

**Comment by pippinsplugins** [comment]
What do you think? Upgrade routine or no?

**Comment by sumobi** [comment]
@pippinsplugins I don't mind either way but I think some people might have put some effort into their rejection text area and if it suddenly goes away they could be sad.

**Comment by pippinsplugins** [comment]
I'm going to do an upgrade routine.

**Comment by pippinsplugins** [comment]
@sumobi Could you test the upgrade routine here for me?

To do that, set up subject and message in the fields that we have removed but leave the ones we have left empty.

I have set it up so that if the bad (duplicate) fields were used *but* the good (remaining) fields were not, the settings get copied over.

**Comment by sumobi** [comment]
@pippinsplugins Worked fine for me. There was probably an easier way to test but my brain told me to paste the old rejected textarea code back, clear out the content in the new one and update the version number in the main plugin file to 1.7.11. Upon refreshing the options the content of the old rejection textarea had been copied to the new one.
